<script setup lang="ts">
import { h, onMounted, ref, watch } from "vue"
import { useRoute, useRouter, RouterLink } from "vue-router"
import { ArrowLeft } from "lucide-vue-next"
import { NButton, NCard, NDataTable, NDescriptions, NDescriptionsItem, NInput, NInputNumber, NModal, NSpace, NTabPane, NTabs, type DataTableColumns } from "naive-ui"
import KpiCard from "@/components/common/KpiCard.vue"
import StatusTag from "@/components/common/StatusTag.vue"
import ErrorState from "@/components/common/ErrorState.vue"
import { feedback } from "@/lib/feedback"
import { fmtDateTime, fmtVnd } from "@/lib/format"
import { labelForVtKind, labelForVtSide } from "@/lib/labels"
import { vtApi, type VTAccountRow, type VTAccountStats, type VTLedgerEntry, type VTOrder, type VTPosition, type VTSettlement, type VTTrade } from "@/lib/api/vt"

const route = useRoute(); const router = useRouter(); const accountId = String(route.params.accountId)
const account = ref<VTAccountRow | null>(null); const stats = ref<VTAccountStats | null>(null); const loading = ref(true); const error = ref<string | null>(null); const activeTab = ref("positions")
const positions = ref<VTPosition[]>([]); const orders = ref<VTOrder[]>([]); const trades = ref<VTTrade[]>([]); const ledger = ref<VTLedgerEntry[]>([]); const settlements = ref<VTSettlement[]>([])
const cashOpen = ref(false); const cashAmount = ref(0); const cashReason = ref("")
async function load() { loading.value = true; error.value = null; try { const [acct, s] = await Promise.all([vtApi.getAccount(accountId), vtApi.getStats(accountId)]); account.value = acct; stats.value = s; await loadTab() } catch (err) { error.value = err instanceof Error ? err.message : "Không thể tải tài khoản" } finally { loading.value = false } }
async function loadTab() { if (activeTab.value === "positions") positions.value = await vtApi.listPositions(accountId); if (activeTab.value === "orders") orders.value = (await vtApi.listOrders(accountId, { page: 1, pageSize: 100 })).items; if (activeTab.value === "trades") trades.value = (await vtApi.listTrades(accountId, { page: 1, pageSize: 100 })).items; if (activeTab.value === "ledger") ledger.value = (await vtApi.listLedger(accountId, { page: 1, pageSize: 100 })).items; if (activeTab.value === "settlements") settlements.value = (await vtApi.listSettlements(accountId, { page: 1, pageSize: 100 })).items }
function freeze() { const reason = ref(""); feedback.dialog?.warning({ title: "Khóa tài khoản?", content: () => h(NInput, { value: reason.value, type: "textarea", placeholder: "Lý do", onUpdateValue: (v: string) => { reason.value = v } }), positiveText: "Khóa", negativeText: "Hủy", onPositiveClick: async () => { if (!reason.value.trim()) { feedback.message?.error("Lý do bắt buộc"); return false } account.value = await vtApi.freeze(accountId, reason.value); feedback.message?.success("Đã khóa tài khoản") } }) }
function unfreeze() { feedback.dialog?.warning({ title: "Mở khóa tài khoản?", positiveText: "Mở khóa", negativeText: "Hủy", onPositiveClick: async () => { account.value = await vtApi.unfreeze(accountId); feedback.message?.success("Đã mở khóa") } }) }
async function cashAdjust() { if (!cashReason.value.trim() || cashAmount.value === 0) { feedback.message?.error("Số tiền và lý do bắt buộc"); return } const res = await vtApi.cashAdjust(accountId, cashAmount.value, cashReason.value); account.value = res.account; feedback.message?.success(`Số dư mới: ${fmtVnd(res.newCashAvailableVnd)}`); cashOpen.value = false; cashAmount.value = 0; cashReason.value = "" }
function resetAccount() { if (!account.value) return; feedback.dialog?.warning({ title: "Đặt lại tài khoản?", content: account.value.userEmail ?? account.value.userId, positiveText: "Đặt lại", negativeText: "Hủy", onPositiveClick: async () => { await vtApi.reset(account.value!.userId); feedback.message?.success("Đã đặt lại tài khoản"); await load() } }) }
watch(activeTab, () => void loadTab())
onMounted(() => void load())
const positionColumns: DataTableColumns<VTPosition> = [{ title: "Mã", key: "symbol" }, { title: "Tổng SL", key: "quantityTotal" }, { title: "Có thể bán", key: "quantitySellable" }, { title: "Giá vốn TB", key: "avgCostVnd", render: (row) => fmtVnd(row.avgCostVnd) }]
const orderColumns: DataTableColumns<VTOrder> = [{ title: "Mã", key: "symbol" }, { title: "Chiều", key: "side", render: (row) => labelForVtSide(row.side) }, { title: "SL", key: "quantity" }, { title: "Trạng thái", key: "status", render: (row) => h(StatusTag, { status: row.status }) }, { title: "Tạo lúc", key: "createdAt", render: (row) => fmtDateTime(row.createdAt) }]
const tradeColumns: DataTableColumns<VTTrade> = [{ title: "Mã", key: "symbol" }, { title: "Chiều", key: "side", render: (row) => labelForVtSide(row.side) }, { title: "SL", key: "quantity" }, { title: "Giá", key: "priceVnd", render: (row) => fmtVnd(row.priceVnd) }, { title: "Khớp lúc", key: "tradedAt", render: (row) => fmtDateTime(row.tradedAt) }]
const ledgerColumns: DataTableColumns<VTLedgerEntry> = [{ title: "Loại", key: "kind", render: (row) => labelForVtKind(row.kind) }, { title: "Số tiền", key: "amountVnd", render: (row) => fmtVnd(row.amountVnd) }, { title: "Số dư sau", key: "balanceAfterVnd", render: (row) => fmtVnd(row.balanceAfterVnd) }, { title: "Ghi chú", key: "note" }, { title: "Tạo lúc", key: "createdAt", render: (row) => fmtDateTime(row.createdAt) }]
const settlementColumns: DataTableColumns<VTSettlement> = [{ title: "Loại", key: "kind", render: (row) => labelForVtKind(row.kind) }, { title: "Số lượng", key: "amount" }, { title: "Mã", key: "symbol" }, { title: "Đến hạn", key: "dueDate" }, { title: "Trạng thái", key: "status", render: (row) => h(StatusTag, { status: row.status }) }]
</script>
<template><div class="page-stack"><div class="page-header"><div><n-button quaternary size="small" @click="router.back()"><template #icon><ArrowLeft :size="16" /></template>Quay lại</n-button><h1 class="page-title">Chi tiết tài khoản giao dịch ảo</h1><p v-if="account" class="page-subtitle"><RouterLink :to="`/users/${account.userId}`">{{ account.userEmail ?? account.userId }}</RouterLink></p></div><n-space v-if="account"><n-button secondary @click="account.frozenAt ? unfreeze() : freeze()">{{ account.frozenAt ? 'Mở khóa' : 'Khóa' }}</n-button><n-button secondary @click="cashOpen = true">Điều chỉnh tiền</n-button><n-button type="error" @click="resetAccount">Đặt lại</n-button></n-space></div><ErrorState v-if="error" :message="error" @retry="load" /><div class="grid-kpis"><KpiCard label="Tiền khả dụng" :value="fmtVnd(account?.cashAvailableVnd ?? 0)" :loading="loading" /><KpiCard label="Tiền giữ" :value="fmtVnd(account?.cashReservedVnd ?? 0)" :loading="loading" /><KpiCard label="Lệnh/GD" :value="stats ? `${stats.totalOrders}/${stats.totalTrades}` : '-'" :loading="loading" /><KpiCard label="PnL" :value="fmtVnd(stats?.realizedPnlVnd ?? 0)" :loading="loading" /></div><n-card v-if="account"><n-descriptions :column="2"><n-descriptions-item label="Trạng thái"><StatusTag :status="account.status" /></n-descriptions-item><n-descriptions-item label="Kích hoạt">{{ account.activatedAt ? fmtDateTime(account.activatedAt) : '-' }}</n-descriptions-item><n-descriptions-item v-if="account.freezeReason" label="Lý do khóa">{{ account.freezeReason }}</n-descriptions-item></n-descriptions></n-card><n-tabs v-model:value="activeTab" type="line" :animated="false"><n-tab-pane name="positions" tab="Vị thế"><n-data-table :columns="positionColumns" :data="positions" /></n-tab-pane><n-tab-pane name="orders" tab="Lệnh"><n-data-table :columns="orderColumns" :data="orders" /></n-tab-pane><n-tab-pane name="trades" tab="Giao dịch"><n-data-table :columns="tradeColumns" :data="trades" /></n-tab-pane><n-tab-pane name="ledger" tab="Sổ cái"><n-data-table :columns="ledgerColumns" :data="ledger" /></n-tab-pane><n-tab-pane name="settlements" tab="T+N"><n-data-table :columns="settlementColumns" :data="settlements" /></n-tab-pane></n-tabs><n-modal v-model:show="cashOpen" preset="card" title="Điều chỉnh tiền" style="max-width:420px"><n-space vertical><n-input-number v-model:value="cashAmount" placeholder="Số tiền" /><n-input v-model:value="cashReason" type="textarea" placeholder="Lý do" /><n-space justify="end"><n-button secondary @click="cashOpen=false">Hủy</n-button><n-button type="primary" @click="cashAdjust">Lưu</n-button></n-space></n-space></n-modal></div></template>
