<script setup lang="ts">
import { onMounted, reactive, ref } from "vue"
import { NButton, NCard, NForm, NFormItem, NInput, NInputNumber, NSpace, NSwitch } from "naive-ui"
import ErrorState from "@/components/common/ErrorState.vue"
import { feedback } from "@/lib/feedback"
import { fmtDateTime, fmtVnd } from "@/lib/format"
import { vtApi, type VTConfigData } from "@/lib/api/vt"

const config = ref<VTConfigData | null>(null); const loading = ref(true); const saving = ref(false); const error = ref<string | null>(null)
const form = reactive({ initialCashVnd: 0, buyFeeRateBps: 0, sellFeeRateBps: 0, sellTaxRateBps: 0, settlementMode: "T2", boardLotSize: 100, tradingEnabled: true, holidaysText: "" })
async function load() { loading.value = true; error.value = null; try { config.value = await vtApi.getConfig(); Object.assign(form, { initialCashVnd: config.value.initialCashVnd, buyFeeRateBps: config.value.buyFeeRateBps, sellFeeRateBps: config.value.sellFeeRateBps, sellTaxRateBps: config.value.sellTaxRateBps, settlementMode: config.value.settlementMode, boardLotSize: config.value.boardLotSize, tradingEnabled: config.value.tradingEnabled, holidaysText: config.value.holidays.join("\n") }) } catch (err) { error.value = err instanceof Error ? err.message : "Không thể tải cấu hình" } finally { loading.value = false } }
async function save() { saving.value = true; try { config.value = await vtApi.updateConfig({ initialCashVnd: form.initialCashVnd, buyFeeRateBps: form.buyFeeRateBps, sellFeeRateBps: form.sellFeeRateBps, sellTaxRateBps: form.sellTaxRateBps, settlementMode: form.settlementMode, boardLotSize: form.boardLotSize, tradingEnabled: form.tradingEnabled, holidays: form.holidaysText.split(/\n|,/).map((v) => v.trim()).filter(Boolean) }); feedback.message?.success("Đã lưu cấu hình") } catch (err) { feedback.message?.error(err instanceof Error ? err.message : "Lưu thất bại") } finally { saving.value = false } }
onMounted(() => void load())
</script>
<template><div class="page-stack"><div class="page-header"><div><h1 class="page-title">Cấu hình giao dịch ảo</h1><p v-if="config" class="page-subtitle">Cập nhật {{ fmtDateTime(config.updatedAt) }} · Tiền ban đầu {{ fmtVnd(config.initialCashVnd) }}</p></div><n-button type="primary" :loading="saving" @click="save">Lưu</n-button></div><ErrorState v-if="error" :message="error" @retry="load" /><n-card :loading="loading"><n-form label-placement="top"><n-space wrap><n-form-item label="Tiền ban đầu"><n-input-number v-model:value="form.initialCashVnd" :min="0" /></n-form-item><n-form-item label="Phí mua (bps)"><n-input-number v-model:value="form.buyFeeRateBps" :min="0" /></n-form-item><n-form-item label="Phí bán (bps)"><n-input-number v-model:value="form.sellFeeRateBps" :min="0" /></n-form-item><n-form-item label="Thuế bán (bps)"><n-input-number v-model:value="form.sellTaxRateBps" :min="0" /></n-form-item><n-form-item label="Lô giao dịch"><n-input-number v-model:value="form.boardLotSize" :min="1" /></n-form-item><n-form-item label="Cho phép giao dịch"><n-switch v-model:value="form.tradingEnabled" /></n-form-item></n-space><n-form-item label="Chế độ tất toán"><n-input v-model:value="form.settlementMode" /></n-form-item><n-form-item label="Ngày nghỉ"><n-input v-model:value="form.holidaysText" type="textarea" :rows="6" /></n-form-item></n-form></n-card></div></template>
