import type { GlobalThemeOverrides } from "naive-ui"

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    fontFamily: "'Manrope', system-ui, sans-serif",
    fontFamilyMono: "'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
    borderRadius: "8px",
    borderRadiusSmall: "6px",
    bodyColor: "#F6F8FC",
    cardColor: "#FFFFFF",
    modalColor: "#FFFFFF",
    popoverColor: "#FFFFFF",
    tableColor: "#FFFFFF",
    primaryColor: "#2563EB",
    primaryColorHover: "#1D4ED8",
    primaryColorPressed: "#1E40AF",
    primaryColorSuppl: "#2563EB",
    successColor: "#059669",
    warningColor: "#D97706",
    errorColor: "#DC2626",
    infoColor: "#0284C7",
    textColorBase: "#111827",
    textColor1: "#0F172A",
    textColor2: "#334155",
    textColor3: "#64748B",
    borderColor: "#E2E8F0",
    dividerColor: "#E2E8F0",
    inputColor: "#F8FAFC",
    codeColor: "#EEF2FF",
  },
  Layout: {
    color: "#F6F8FC",
    siderColor: "#FFFFFF",
    headerColor: "#FFFFFF",
  },
  Card: {
    color: "#FFFFFF",
    colorModal: "#FFFFFF",
    borderColor: "#E2E8F0",
  },
  DataTable: {
    thColor: "#F8FAFC",
    tdColor: "#FFFFFF",
    borderColor: "#E2E8F0",
  },
  Menu: {
    itemTextColor: "#475569",
    itemTextColorActive: "#1D4ED8",
    itemColorActive: "#EFF6FF",
    itemIconColorActive: "#2563EB",
  },
  LoadingBar: {
    colorLoading: "#2563EB",
    colorError: "#DC2626",
  },
}
