"""Canonical display name mapping for 38 TA indicators.

Maps indicator_id to Vietnamese display names and types (num|signal).
"""

INDICATOR_DISPLAY: dict[str, str] = {
    "ma_5": "MA5",
    "ma_20": "MA20",
    "ma_50": "MA50",
    "ma_200": "MA200",
    "ma_stack_bull": "MA5 > MA20 > MA50 > MA200",
    "uptrend": "MA50 > MA200",
    "death_cross": "MA20 cắt xuống MA50",
    "ma_20_slope": "Độ dốc MA20",
    "dist_ma_20": "Khoảng cách giá tới MA20",
    "dist_ma_200": "Khoảng cách giá tới MA200",
    "rsi_14": "RSI 14",
    "macd_hist": "Histogram MACD",
    "macd_bull_cross": "MACD cắt lên Signal",
    "macd_bear_cross": "MACD cắt xuống Signal",
    "roc_20d": "ROC 20 phiên",
    "atr_14": "ATR 14",
    "atr_pct": "ATR theo % giá",
    "bb_width": "Độ rộng dải Bollinger",
    "bb_squeeze": "Bollinger thắt hẹp",
    "bb_breakout_down": "Giá phá xuống Bollinger dưới",
    "vol_ma_20": "MA20 của khối lượng",
    "vol_zscore": "Độ bất thường khối lượng",
    "obv": "OBV",
    "obv_ma_20": "MA20 của OBV",
    "high_20": "Đỉnh 20 phiên",
    "high_52w": "Đỉnh 52 tuần",
    "dist_52w_high": "Khoảng cách tới đỉnh 52 tuần",
    "breakout_20d": "Phá đỉnh 20 phiên",
    "breakout_52w": "Phá đỉnh 52 tuần",
    "low_20": "Đáy 20 phiên",
    "low_52w": "Đáy 52 tuần",
    "dist_52w_low": "Khoảng cách tới đáy 52 tuần",
    "breakdown_20d": "Thủng đáy 20 phiên",
    "breakdown_52w": "Thủng đáy 52 tuần",
    "hammer": "Nến búa",
    "bull_engulfing": "Nến nhấn chìm tăng",
    "bear_engulfing": "Nến nhấn chìm giảm",
    "shooting_star": "Nến sao băng",
}

INDICATOR_KIND: dict[str, str] = {
    "ma_5": "num",
    "ma_20": "num",
    "ma_50": "num",
    "ma_200": "num",
    "ma_stack_bull": "signal",
    "uptrend": "signal",
    "death_cross": "signal",
    "ma_20_slope": "num",
    "dist_ma_20": "num",
    "dist_ma_200": "num",
    "rsi_14": "num",
    "macd_hist": "num",
    "macd_bull_cross": "signal",
    "macd_bear_cross": "signal",
    "roc_20d": "num",
    "atr_14": "num",
    "atr_pct": "num",
    "bb_width": "num",
    "bb_squeeze": "signal",
    "bb_breakout_down": "signal",
    "vol_ma_20": "num",
    "vol_zscore": "num",
    "obv": "num",
    "obv_ma_20": "num",
    "high_20": "num",
    "high_52w": "num",
    "dist_52w_high": "num",
    "breakout_20d": "signal",
    "breakout_52w": "signal",
    "low_20": "num",
    "low_52w": "num",
    "dist_52w_low": "num",
    "breakdown_20d": "signal",
    "breakdown_52w": "signal",
    "hammer": "signal",
    "bull_engulfing": "signal",
    "bear_engulfing": "signal",
    "shooting_star": "signal",
}


def display_name(indicator_id: str) -> str:
    """Return the display name for an indicator, or the id if not found."""
    return INDICATOR_DISPLAY.get(indicator_id, indicator_id)
