-- Generated by scripts/generate-v2-schema.py; do not edit by hand.
-- Standalone IQX backend-v2 schema: 65 tables, no legacy data migration.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE alert_side AS ENUM ('buy', 'sell');

CREATE TYPE cap0_ly_do_doi_thuong AS ENUM ('cong_ty_toi_biet', 'nguoi_quen_gioi_thieu', 'thay_tren_mang', 'gia_dang_tang', 'thu_cho_biet');

CREATE TYPE cap0_placement_experience AS ENUM ('never', 'unsure', 'regular');

CREATE TYPE cap1_cam_xuc AS ENUM ('binh_tinh', 'so', 'hoi_tiec', 'khong_ro');

CREATE TYPE cap1_ly_do AS ENUM ('ky_thuat', 'dong_tien', 'noi_bo', 'tin_tuc', 'dinh_gia');

CREATE TYPE cap1_trang_thai_luc_dat AS ENUM ('ung_ho', 'trung_tinh', 'can_chu_y', 'nguoc_chieu');

CREATE TYPE cap2_phuong_phap_sl_tp AS ENUM ('ho_tro_khang_cu', 'bien_do_dao_dong');

CREATE TYPE cap3_cach_khoi_luong AS ENUM ('khau_vi_tu_tin', 'chia_deu');

CREATE TYPE cap3_khau_vi_rui_ro AS ENUM ('than_trong', 'can_bang', 'tan_cong');

CREATE TYPE payment_order_status AS ENUM ('pending', 'paid', 'failed', 'cancelled', 'refunded');

CREATE TYPE settlement_mode AS ENUM ('T0', 'T2');

CREATE TYPE subscription_status AS ENUM ('active', 'expired', 'cancelled');

CREATE TYPE user_role AS ENUM ('admin', 'user', 'premium');

CREATE TYPE user_status AS ENUM ('active', 'inactive', 'suspended', 'deleted');

CREATE TYPE vt_account_status AS ENUM ('active', 'suspended');

CREATE TYPE vt_order_side AS ENUM ('buy', 'sell');

CREATE TYPE vt_order_status AS ENUM ('pending', 'filled', 'cancelled', 'expired', 'rejected');

CREATE TYPE vt_order_type AS ENUM ('market', 'limit');

CREATE TYPE vt_settlement_kind AS ENUM ('buy_qty_release', 'sell_cash_release');

CREATE TYPE vt_settlement_status AS ENUM ('pending', 'settled');

CREATE TABLE ai_insight_history (
	symbol VARCHAR(10) NOT NULL, 
	session_date DATE NOT NULL, 
	payload JSONB NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_ai_insight_history PRIMARY KEY (id), 
	CONSTRAINT uq_ai_insight_symbol_date UNIQUE (symbol, session_date)
);

CREATE INDEX ix_ai_insight_history_session_date ON ai_insight_history (session_date);

CREATE INDEX ix_ai_insight_history_symbol ON ai_insight_history (symbol);

CREATE TABLE alert_signals (
	key VARCHAR(40) NOT NULL, 
	side alert_side NOT NULL, 
	ta_name VARCHAR(60) NOT NULL, 
	message_title VARCHAR(200) NOT NULL, 
	combination JSONB NOT NULL, 
	is_enabled BOOLEAN DEFAULT 'true' NOT NULL, 
	sort_order INTEGER DEFAULT '0' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_alert_signals PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_alert_signals_key ON alert_signals (key);

CREATE TABLE analysis_history (
	public_id VARCHAR(50) NOT NULL, 
	session_date DATE NOT NULL, 
	generated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	session_type VARCHAR(30) NOT NULL, 
	report_type VARCHAR(16) DEFAULT 'daily' NOT NULL, 
	headline TEXT NOT NULL, 
	tagline JSONB NOT NULL, 
	paragraphs JSONB NOT NULL, 
	scenarios JSONB NOT NULL, 
	watchlist JSONB, 
	unexplained TEXT, 
	meta JSONB, 
	is_published BOOLEAN DEFAULT 'true' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_analysis_history PRIMARY KEY (id), 
	CONSTRAINT uq_analysis_session_date_report_type UNIQUE (session_date, report_type), 
	CONSTRAINT uq_analysis_history_public_id UNIQUE (public_id)
);

CREATE INDEX ix_analysis_history_report_type ON analysis_history (report_type);

CREATE INDEX ix_analysis_history_session_date ON analysis_history (session_date);

CREATE INDEX ix_analysis_history_session_type ON analysis_history (session_type);

CREATE TABLE market_data_snapshot (
	id SERIAL NOT NULL, 
	snapshot_date DATE NOT NULL, 
	asset_category VARCHAR(32) NOT NULL, 
	symbol VARCHAR(32) NOT NULL, 
	name VARCHAR(128) NOT NULL, 
	last_price NUMERIC(18, 6) NOT NULL, 
	previous_close NUMERIC(18, 6) NOT NULL, 
	change_value NUMERIC(18, 6) NOT NULL, 
	change_percent NUMERIC(10, 4) NOT NULL, 
	day_high NUMERIC(18, 6), 
	day_low NUMERIC(18, 6), 
	volume BIGINT, 
	currency VARCHAR(8), 
	market_state VARCHAR(16), 
	market_time TIMESTAMP WITH TIME ZONE, 
	source VARCHAR(32) DEFAULT 'yahoo' NOT NULL, 
	stale BOOLEAN DEFAULT false NOT NULL, 
	fetched_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_market_data_snapshot PRIMARY KEY (id), 
	CONSTRAINT uq_snapshot_date_symbol UNIQUE (snapshot_date, symbol)
);

CREATE INDEX ix_market_data_snapshot_asset_category ON market_data_snapshot (asset_category);

CREATE INDEX ix_market_data_snapshot_snapshot_date ON market_data_snapshot (snapshot_date);

CREATE TABLE premium_plans (
	code VARCHAR(50) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	description TEXT, 
	price_vnd INTEGER NOT NULL, 
	duration_days INTEGER NOT NULL, 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	sort_order INTEGER DEFAULT '0' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_premium_plans PRIMARY KEY (id), 
	CONSTRAINT uq_premium_plans_code UNIQUE (code)
);

CREATE TABLE sector_median_cache (
	icb_lv2 VARCHAR(100) NOT NULL, 
	asof_date DATE NOT NULL, 
	medians JSONB NOT NULL, 
	peer_count INTEGER DEFAULT 0 NOT NULL, 
	computed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_sector_median_cache PRIMARY KEY (id), 
	CONSTRAINT uq_sector_median_icb_asof UNIQUE (icb_lv2, asof_date)
);

CREATE INDEX ix_sector_median_cache_asof_date ON sector_median_cache (asof_date);

CREATE INDEX ix_sector_median_cache_icb_lv2 ON sector_median_cache (icb_lv2);

CREATE TABLE symbols (
	symbol VARCHAR(10) NOT NULL, 
	name VARCHAR(500), 
	short_name VARCHAR(255), 
	exchange VARCHAR(20), 
	asset_type VARCHAR(50) DEFAULT 'stock', 
	is_index BOOLEAN DEFAULT 'false' NOT NULL, 
	current_price_vnd BIGINT, 
	target_price_vnd BIGINT, 
	upside_pct FLOAT, 
	logo_url VARCHAR(2048), 
	logo_source VARCHAR(30), 
	icb_lv1 VARCHAR(100), 
	icb_lv2 VARCHAR(100), 
	source VARCHAR(50), 
	source_url VARCHAR(2048), 
	last_synced_at TIMESTAMP WITH TIME ZONE, 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_symbols PRIMARY KEY (id)
);

CREATE INDEX ix_symbols_asset_type ON symbols (asset_type);

CREATE INDEX ix_symbols_exchange ON symbols (exchange);

CREATE INDEX ix_symbols_is_index ON symbols (is_index);

CREATE UNIQUE INDEX ix_symbols_symbol ON symbols (symbol);

CREATE TABLE users (
	email VARCHAR(320) NOT NULL, 
	hashed_password VARCHAR(1024) NOT NULL, 
	phone_number VARCHAR(30), 
	phone_country_code VARCHAR(5), 
	phone_national_number VARCHAR(20), 
	phone_e164 VARCHAR(20), 
	phone_verified_at TIMESTAMP WITH TIME ZONE, 
	full_name VARCHAR(200) NOT NULL, 
	avatar_url VARCHAR(2048), 
	date_of_birth DATE, 
	gender VARCHAR(20), 
	country VARCHAR(100), 
	province_state VARCHAR(100), 
	city VARCHAR(100), 
	district VARCHAR(100), 
	ward VARCHAR(100), 
	street_address VARCHAR(500), 
	postal_code VARCHAR(20), 
	role user_role DEFAULT 'user' NOT NULL, 
	status user_status DEFAULT 'active' NOT NULL, 
	telegram_chat_id VARCHAR(32), 
	telegram_linked_at TIMESTAMP WITH TIME ZONE, 
	is_email_verified BOOLEAN DEFAULT 'false' NOT NULL, 
	email_verified_at TIMESTAMP WITH TIME ZONE, 
	last_login_at TIMESTAMP WITH TIME ZONE, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_users PRIMARY KEY (id), 
	CONSTRAINT uq_users_phone_e164 UNIQUE (phone_e164)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);

CREATE UNIQUE INDEX ix_users_phone_number ON users (phone_number);

CREATE UNIQUE INDEX ix_users_telegram_chat_id ON users (telegram_chat_id);

CREATE TABLE admin_audit_log (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	admin_user_id UUID, 
	action VARCHAR(80) NOT NULL, 
	target_entity VARCHAR(60), 
	target_id VARCHAR(100), 
	payload_before JSONB, 
	payload_after JSONB, 
	note VARCHAR(1000), 
	ip VARCHAR(45), 
	user_agent VARCHAR(500), 
	request_id VARCHAR(40), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_admin_audit_log PRIMARY KEY (id), 
	CONSTRAINT fk_admin_audit_log_admin_user_id_users FOREIGN KEY(admin_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_admin_audit_log_action ON admin_audit_log (action);

CREATE INDEX ix_admin_audit_log_action_created ON admin_audit_log (action, created_at);

CREATE INDEX ix_admin_audit_log_admin_created ON admin_audit_log (admin_user_id, created_at);

CREATE INDEX ix_admin_audit_log_admin_user_id ON admin_audit_log (admin_user_id);

CREATE INDEX ix_admin_audit_log_created_at ON admin_audit_log (created_at);

CREATE INDEX ix_admin_audit_log_entity_target ON admin_audit_log (target_entity, target_id);

CREATE TABLE analysis_claims (
	analysis_id UUID NOT NULL, 
	session_date DATE NOT NULL, 
	claim_text TEXT NOT NULL, 
	claim_type VARCHAR(30) NOT NULL, 
	conditions JSONB NOT NULL, 
	predicted_outcome TEXT, 
	status VARCHAR(20) DEFAULT 'pending' NOT NULL, 
	verified_at TIMESTAMP WITH TIME ZONE, 
	verification_note TEXT, 
	expires_at DATE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_analysis_claims PRIMARY KEY (id), 
	CONSTRAINT fk_analysis_claims_analysis_id_analysis_history FOREIGN KEY(analysis_id) REFERENCES analysis_history (id) ON DELETE CASCADE
);

CREATE INDEX ix_analysis_claims_analysis_id ON analysis_claims (analysis_id);

CREATE INDEX ix_analysis_claims_session_date ON analysis_claims (session_date);

CREATE INDEX ix_analysis_claims_status_date ON analysis_claims (status, session_date);

CREATE TABLE backtest_strategies (
	user_id UUID NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	symbol VARCHAR(20), 
	config JSONB NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_backtest_strategies PRIMARY KEY (id), 
	CONSTRAINT uq_backtest_strategies_user_name UNIQUE (user_id, name), 
	CONSTRAINT fk_backtest_strategies_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_backtest_strategies_symbol ON backtest_strategies (symbol);

CREATE INDEX ix_backtest_strategies_user_id ON backtest_strategies (user_id);

CREATE TABLE bot_accounts (
	user_id UUID NOT NULL, 
	initial_cash_vnd BIGINT NOT NULL, 
	cash_vnd BIGINT NOT NULL, 
	status VARCHAR(16) DEFAULT 'active' NOT NULL, 
	activated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_bot_accounts PRIMARY KEY (id), 
	CONSTRAINT uq_bot_accounts_user_id UNIQUE (user_id), 
	CONSTRAINT ck_bot_accounts_bot_initial_cash_v1 CHECK (initial_cash_vnd = 100000000), 
	CONSTRAINT ck_bot_accounts_bot_cash_non_negative CHECK (cash_vnd >= 0), 
	CONSTRAINT ck_bot_accounts_bot_account_status CHECK (status IN ('active', 'suspended')), 
	CONSTRAINT fk_bot_accounts_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_bot_accounts_user_id ON bot_accounts (user_id);

CREATE TABLE bot_mascot_profiles (
	user_id UUID NOT NULL, 
	mascot_rules_version INTEGER DEFAULT 1 NOT NULL, 
	assignment_status VARCHAR(32) NOT NULL, 
	mascot_id VARCHAR(24), 
	dominant_layer VARCHAR(24), 
	assignment_basis VARCHAR(32), 
	window_start TIMESTAMP WITH TIME ZONE, 
	window_end TIMESTAMP WITH TIME ZONE NOT NULL, 
	valid_pair_count INTEGER DEFAULT 0 NOT NULL, 
	match_counts JSONB NOT NULL, 
	tied_layers JSONB NOT NULL, 
	selected_assessment_refs JSONB NOT NULL, 
	dataset_hash VARCHAR(64) NOT NULL, 
	excluded_records_summary JSONB NOT NULL, 
	assigned_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_bot_mascot_profiles PRIMARY KEY (id), 
	CONSTRAINT uq_bot_mascot_profiles_user_id UNIQUE (user_id, mascot_rules_version), 
	CONSTRAINT ck_bot_mascot_profiles_valid_pair_count CHECK (valid_pair_count >= 0), 
	CONSTRAINT ck_bot_mascot_profiles_rules_version CHECK (mascot_rules_version > 0), 
	CONSTRAINT ck_bot_mascot_profiles_assignment_status CHECK (assignment_status IN ('assigned', 'pending_data_repair')), 
	CONSTRAINT ck_bot_mascot_profiles_mascot_id CHECK (mascot_id IS NULL OR mascot_id IN ('bach_ho', 'thanh_long', 'loc_huou', 'phung_hoang', 'kim_quy')), 
	CONSTRAINT ck_bot_mascot_profiles_dominant_layer CHECK (dominant_layer IS NULL OR dominant_layer IN ('ky_thuat', 'dong_tien', 'noi_bo', 'tin_tuc', 'dinh_gia')), 
	CONSTRAINT ck_bot_mascot_profiles_assignment_basis CHECK (assignment_basis IS NULL OR assignment_basis IN ('ai_match_count', 'stable_tie_break', 'zero_match_tie_break')), 
	CONSTRAINT ck_bot_mascot_profiles_window_order CHECK (window_start IS NULL OR window_start <= window_end), 
	CONSTRAINT ck_bot_mascot_profiles_assignment_shape CHECK ((assignment_status = 'assigned' AND valid_pair_count > 0 AND mascot_id IS NOT NULL AND dominant_layer IS NOT NULL AND assignment_basis IS NOT NULL AND window_start IS NOT NULL AND assigned_at IS NOT NULL) OR (assignment_status = 'pending_data_repair' AND valid_pair_count = 0 AND mascot_id IS NULL AND dominant_layer IS NULL AND assignment_basis IS NULL AND assigned_at IS NULL)), 
	CONSTRAINT ck_bot_mascot_profiles_assigned_after_window CHECK (assigned_at IS NULL OR assigned_at >= window_end), 
	CONSTRAINT fk_bot_mascot_profiles_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_bot_mascot_profiles_user_id ON bot_mascot_profiles (user_id);

CREATE TABLE cap0_progress (
	user_id UUID NOT NULL, 
	entered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	virtual_balance_init BIGINT DEFAULT '100000000' NOT NULL, 
	task_1_done_at TIMESTAMP WITH TIME ZONE, 
	task_2_done_at TIMESTAMP WITH TIME ZONE, 
	task_3_done_at TIMESTAMP WITH TIME ZONE, 
	task_4_done_at TIMESTAMP WITH TIME ZONE, 
	task_5_done_at TIMESTAMP WITH TIME ZONE, 
	task1_star_clicked BOOLEAN DEFAULT 'false' NOT NULL, 
	task5_debrief_done BOOLEAN DEFAULT 'false' NOT NULL, 
	graduated_at TIMESTAMP WITH TIME ZONE, 
	time_to_graduate_hours FLOAT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap0_progress PRIMARY KEY (id), 
	CONSTRAINT uq_cap0_progress_user_id UNIQUE (user_id), 
	CONSTRAINT fk_cap0_progress_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap0_progress_user_id ON cap0_progress (user_id);

CREATE TABLE cap1_progress (
	user_id UUID NOT NULL, 
	entered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	da_xem_tour BOOLEAN DEFAULT 'false' NOT NULL, 
	task_1_done_at TIMESTAMP WITH TIME ZONE, 
	task_2_done_at TIMESTAMP WITH TIME ZONE, 
	task_3_done_at TIMESTAMP WITH TIME ZONE, 
	task_4_done_at TIMESTAMP WITH TIME ZONE, 
	task_5_done_at TIMESTAMP WITH TIME ZONE, 
	so_ly_do_da_dung INTEGER DEFAULT '0' NOT NULL, 
	so_lenh_ly_do_ung_ho INTEGER DEFAULT '0' NOT NULL, 
	so_lenh_thuc_chien INTEGER DEFAULT '0' NOT NULL, 
	graduated_at TIMESTAMP WITH TIME ZONE, 
	time_to_graduate_hours FLOAT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap1_progress PRIMARY KEY (id), 
	CONSTRAINT uq_cap1_progress_user_id UNIQUE (user_id), 
	CONSTRAINT fk_cap1_progress_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap1_progress_user_id ON cap1_progress (user_id);

CREATE TABLE cap2_alert_session_state (
	user_id UUID NOT NULL, 
	session_date DATE NOT NULL, 
	important_shown_count INTEGER DEFAULT '0' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap2_alert_session_state PRIMARY KEY (id), 
	CONSTRAINT uq_cap2_alert_session_state_user_date UNIQUE (user_id, session_date), 
	CONSTRAINT ck_cap2_alert_session_state_cap2_alert_session_state_co_62ee CHECK (important_shown_count >= 0 AND important_shown_count <= 2), 
	CONSTRAINT fk_cap2_alert_session_state_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap2_alert_session_state_session_date ON cap2_alert_session_state (session_date);

CREATE INDEX ix_cap2_alert_session_state_user_id ON cap2_alert_session_state (user_id);

CREATE TABLE cap2_alert_type_state (
	user_id UUID NOT NULL, 
	alert_type VARCHAR(20) NOT NULL, 
	ignored_streak INTEGER DEFAULT '0' NOT NULL, 
	last_ignored_at TIMESTAMP WITH TIME ZONE, 
	last_respected_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap2_alert_type_state PRIMARY KEY (id), 
	CONSTRAINT uq_cap2_alert_type_state_user_type UNIQUE (user_id, alert_type), 
	CONSTRAINT ck_cap2_alert_type_state_cap2_alert_type_state_type CHECK (alert_type IN ('nhoi_lenh', 'cham_cat_lo')), 
	CONSTRAINT ck_cap2_alert_type_state_cap2_alert_type_state_streak_n_86ba CHECK (ignored_streak >= 0), 
	CONSTRAINT fk_cap2_alert_type_state_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap2_alert_type_state_user_id ON cap2_alert_type_state (user_id);

CREATE TABLE cap2_progress (
	user_id UUID NOT NULL, 
	entered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	task_1_done_at TIMESTAMP WITH TIME ZONE, 
	so_lenh_co_cl_tp INTEGER DEFAULT '0' NOT NULL, 
	so_lan_cat_lo_dung INTEGER DEFAULT '0' NOT NULL, 
	so_lan_chot_loi_dung INTEGER DEFAULT '0' NOT NULL, 
	so_lan_thuc_hien_dung INTEGER DEFAULT '0' NOT NULL, 
	chuoi_current INTEGER DEFAULT '0' NOT NULL, 
	chuoi_record INTEGER DEFAULT '0' NOT NULL, 
	last_chuoi_reset_at TIMESTAMP WITH TIME ZONE, 
	graduated_at TIMESTAMP WITH TIME ZONE, 
	time_to_graduate_hours FLOAT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap2_progress PRIMARY KEY (id), 
	CONSTRAINT uq_cap2_progress_user_id UNIQUE (user_id), 
	CONSTRAINT fk_cap2_progress_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap2_progress_user_id ON cap2_progress (user_id);

CREATE TABLE cap3_progress (
	user_id UUID NOT NULL, 
	entered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	khau_vi_da_dat BOOLEAN DEFAULT 'false' NOT NULL, 
	khau_vi cap3_khau_vi_rui_ro, 
	von_ban_dau BIGINT DEFAULT '100000000' NOT NULL, 
	task_1_done_at TIMESTAMP WITH TIME ZONE, 
	task_2_done_at TIMESTAMP WITH TIME ZONE, 
	so_lenh_cap3 INTEGER DEFAULT '0' NOT NULL, 
	lai_pct_cap3 FLOAT DEFAULT '0' NOT NULL, 
	diem_ky_luat_tb_cap3 FLOAT, 
	graduated_at TIMESTAMP WITH TIME ZONE, 
	time_to_graduate_hours FLOAT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap3_progress PRIMARY KEY (id), 
	CONSTRAINT uq_cap3_progress_user_id UNIQUE (user_id), 
	CONSTRAINT fk_cap3_progress_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap3_progress_user_id ON cap3_progress (user_id);

CREATE TABLE cap4_progress (
	user_id UUID NOT NULL, 
	entered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	task_1_done_at TIMESTAMP WITH TIME ZONE, 
	so_lenh_doc_du_5lop INTEGER DEFAULT '0' NOT NULL, 
	vu_khi_lop VARCHAR(32), 
	diem_mu_lop VARCHAR(32), 
	graduated_at TIMESTAMP WITH TIME ZONE, 
	time_to_graduate_hours FLOAT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap4_progress PRIMARY KEY (id), 
	CONSTRAINT uq_cap4_progress_user_id UNIQUE (user_id), 
	CONSTRAINT fk_cap4_progress_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap4_progress_user_id ON cap4_progress (user_id);

CREATE TABLE cap5_hunt_log (
	user_id UUID NOT NULL, 
	symbol VARCHAR(20) NOT NULL, 
	hunt_filter VARCHAR(16) NOT NULL, 
	hunt_signal VARCHAR(200), 
	first_hunted_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_hunted_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	notable_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap5_hunt_log PRIMARY KEY (id), 
	CONSTRAINT uq_cap5_hunt_log_user_symbol UNIQUE (user_id, symbol), 
	CONSTRAINT fk_cap5_hunt_log_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap5_hunt_log_user_id ON cap5_hunt_log (user_id);

CREATE TABLE cap5_progress (
	user_id UUID NOT NULL, 
	entered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	task_1_done_at TIMESTAMP WITH TIME ZONE, 
	task_2_done_at TIMESTAMP WITH TIME ZONE, 
	so_ma_da_san INTEGER DEFAULT '0' NOT NULL, 
	so_ma_mua_tu_watchlist INTEGER DEFAULT '0' NOT NULL, 
	da_xem_tour_sanma BOOLEAN DEFAULT 'false' NOT NULL, 
	best_filter VARCHAR(16), 
	graduated_at TIMESTAMP WITH TIME ZONE, 
	time_to_graduate_hours FLOAT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap5_progress PRIMARY KEY (id), 
	CONSTRAINT uq_cap5_progress_user_id UNIQUE (user_id), 
	CONSTRAINT fk_cap5_progress_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap5_progress_user_id ON cap5_progress (user_id);

CREATE TABLE cap6_progress (
	user_id UUID NOT NULL, 
	entered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	so_lan_xu_ly_nhat_quan INTEGER DEFAULT '0' NOT NULL, 
	so_lan_xu_ly_veto_nhat_quan INTEGER DEFAULT '0' NOT NULL, 
	tong_lai_lenh_cap6_pct FLOAT, 
	da_xem_tour_mauthuan BOOLEAN DEFAULT 'false' NOT NULL, 
	graduated_at TIMESTAMP WITH TIME ZONE, 
	time_to_graduate_hours FLOAT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap6_progress PRIMARY KEY (id), 
	CONSTRAINT uq_cap6_progress_user_id UNIQUE (user_id), 
	CONSTRAINT fk_cap6_progress_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap6_progress_user_id ON cap6_progress (user_id);

CREATE TABLE cap6_skip (
	user_id UUID NOT NULL, 
	symbol VARCHAR(20) NOT NULL, 
	at TIMESTAMP WITH TIME ZONE NOT NULL, 
	conflict_level VARCHAR(8) NOT NULL, 
	had_conflict BOOLEAN, 
	had_veto BOOLEAN, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap6_skip PRIMARY KEY (id), 
	CONSTRAINT fk_cap6_skip_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap6_skip_user_id ON cap6_skip (user_id);

CREATE TABLE cap7_progress (
	user_id UUID NOT NULL, 
	entered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	can_doi_ok BOOLEAN DEFAULT 'false' NOT NULL, 
	graduated_at TIMESTAMP WITH TIME ZONE, 
	time_to_graduate_hours FLOAT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap7_progress PRIMARY KEY (id), 
	CONSTRAINT uq_cap7_progress_user_id UNIQUE (user_id), 
	CONSTRAINT fk_cap7_progress_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap7_progress_user_id ON cap7_progress (user_id);

CREATE TABLE cap8_progress (
	user_id UUID NOT NULL, 
	entered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	so_lenh_thoat_dung_ke_hoach INTEGER DEFAULT '0' NOT NULL, 
	graduated_at TIMESTAMP WITH TIME ZONE, 
	time_to_graduate_hours FLOAT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap8_progress PRIMARY KEY (id), 
	CONSTRAINT uq_cap8_progress_user_id UNIQUE (user_id), 
	CONSTRAINT fk_cap8_progress_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap8_progress_user_id ON cap8_progress (user_id);

CREATE TABLE chart_drawings (
	user_id UUID NOT NULL, 
	symbol VARCHAR(20) NOT NULL, 
	state JSONB NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_chart_drawings PRIMARY KEY (id), 
	CONSTRAINT uq_chart_drawings_user_symbol UNIQUE (user_id, symbol), 
	CONSTRAINT fk_chart_drawings_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_chart_drawings_symbol ON chart_drawings (symbol);

CREATE INDEX ix_chart_drawings_user_id ON chart_drawings (user_id);

CREATE TABLE courses (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	slug VARCHAR(120) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	description TEXT, 
	thumbnail_url VARCHAR(500), 
	level VARCHAR(20) NOT NULL, 
	category VARCHAR(60) NOT NULL, 
	is_premium BOOLEAN DEFAULT false NOT NULL, 
	is_published BOOLEAN DEFAULT false NOT NULL, 
	total_episodes INTEGER DEFAULT 0 NOT NULL, 
	total_duration_seconds INTEGER DEFAULT 0 NOT NULL, 
	created_by_user_id UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_courses PRIMARY KEY (id), 
	CONSTRAINT fk_courses_created_by_user_id_users FOREIGN KEY(created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_courses_catalog ON courses (is_published, is_premium, category);

CREATE INDEX ix_courses_category ON courses (category);

CREATE INDEX ix_courses_created_at ON courses (created_at);

CREATE UNIQUE INDEX ix_courses_slug ON courses (slug);

CREATE TABLE journey_events (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	source VARCHAR(8) NOT NULL, 
	occurred_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	fields JSONB NOT NULL, 
	CONSTRAINT pk_journey_events PRIMARY KEY (id), 
	CONSTRAINT fk_journey_events_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_journey_events_name ON journey_events (name);

CREATE INDEX ix_journey_events_occurred_at ON journey_events (occurred_at);

CREATE INDEX ix_journey_events_user_id ON journey_events (user_id);

CREATE TABLE journey_identity_ui (
	user_id UUID NOT NULL, 
	last_seen_egg_level INTEGER, 
	last_seen_egg_level_at TIMESTAMP WITH TIME ZONE, 
	egg_hatch_seen_at TIMESTAMP WITH TIME ZONE, 
	mascot_reveal_seen_at TIMESTAMP WITH TIME ZONE, 
	mascot_greeted_local_date DATE, 
	last_animated_bot_run_id UUID, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_journey_identity_ui PRIMARY KEY (user_id), 
	CONSTRAINT ck_journey_identity_ui_egg_level CHECK (last_seen_egg_level IS NULL OR last_seen_egg_level BETWEEN 0 AND 6), 
	CONSTRAINT ck_journey_identity_ui_hatch_before_reveal CHECK (mascot_reveal_seen_at IS NULL OR egg_hatch_seen_at IS NOT NULL), 
	CONSTRAINT fk_journey_identity_ui_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE journey_reading_datasets (
	user_id UUID NOT NULL, 
	symbol VARCHAR(10) NOT NULL, 
	trading_date DATE NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	dataset_hash VARCHAR(64) NOT NULL, 
	payload JSONB NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_journey_reading_datasets PRIMARY KEY (id), 
	CONSTRAINT fk_journey_reading_datasets_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_journey_reading_datasets_user_id ON journey_reading_datasets (user_id);

CREATE TABLE premium_payment_orders (
	invoice_number VARCHAR(100) NOT NULL, 
	user_id UUID NOT NULL, 
	plan_id UUID NOT NULL, 
	amount_vnd INTEGER NOT NULL, 
	currency VARCHAR(3) DEFAULT 'VND' NOT NULL, 
	status payment_order_status DEFAULT 'pending' NOT NULL, 
	sepay_transaction_id VARCHAR(200), 
	raw_ipn TEXT, 
	paid_at TIMESTAMP WITH TIME ZONE, 
	grant_type VARCHAR(20), 
	granted_by_user_id UUID, 
	grant_note TEXT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_premium_payment_orders PRIMARY KEY (id), 
	CONSTRAINT fk_premium_payment_orders_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_premium_payment_orders_plan_id_premium_plans FOREIGN KEY(plan_id) REFERENCES premium_plans (id) ON DELETE RESTRICT, 
	CONSTRAINT uq_premium_payment_orders_sepay_transaction_id UNIQUE (sepay_transaction_id), 
	CONSTRAINT fk_premium_payment_orders_granted_by_user_id_users FOREIGN KEY(granted_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX ix_premium_payment_orders_invoice_number ON premium_payment_orders (invoice_number);

CREATE INDEX ix_premium_payment_orders_user_id ON premium_payment_orders (user_id);

CREATE TABLE premium_subscriptions (
	user_id UUID NOT NULL, 
	current_plan_id UUID, 
	current_period_start TIMESTAMP WITH TIME ZONE NOT NULL, 
	current_period_end TIMESTAMP WITH TIME ZONE NOT NULL, 
	status subscription_status DEFAULT 'active' NOT NULL, 
	cancelled_at TIMESTAMP WITH TIME ZONE, 
	cancelled_by_user_id UUID, 
	cancel_reason VARCHAR(1000), 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_premium_subscriptions PRIMARY KEY (id), 
	CONSTRAINT uq_premium_subscriptions_user_id UNIQUE (user_id), 
	CONSTRAINT fk_premium_subscriptions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_premium_subscriptions_current_plan_id_premium_plans FOREIGN KEY(current_plan_id) REFERENCES premium_plans (id) ON DELETE SET NULL, 
	CONSTRAINT fk_premium_subscriptions_cancelled_by_user_id_users FOREIGN KEY(cancelled_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_premium_subscriptions_user_id ON premium_subscriptions (user_id);

CREATE TABLE refresh_tokens (
	user_id UUID NOT NULL, 
	jti VARCHAR(64) NOT NULL, 
	token_family VARCHAR(64) NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	revoked BOOLEAN DEFAULT 'false' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_refresh_tokens PRIMARY KEY (id), 
	CONSTRAINT fk_refresh_tokens_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_refresh_tokens_jti ON refresh_tokens (jti);

CREATE INDEX ix_refresh_tokens_token_family ON refresh_tokens (token_family);

CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE user_alert_rules (
	user_id UUID NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	side alert_side NOT NULL, 
	base_signal_key VARCHAR(40), 
	combination JSONB NOT NULL, 
	is_enabled BOOLEAN DEFAULT 'true' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_user_alert_rules PRIMARY KEY (id), 
	CONSTRAINT fk_user_alert_rules_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_user_alert_rules_user_id ON user_alert_rules (user_id);

CREATE TABLE user_login_history (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	user_id UUID, 
	email VARCHAR(320) NOT NULL, 
	success BOOLEAN NOT NULL, 
	failure_reason VARCHAR(200), 
	ip VARCHAR(45), 
	user_agent VARCHAR(500), 
	login_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_user_login_history PRIMARY KEY (id), 
	CONSTRAINT fk_user_login_history_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_user_login_history_email ON user_login_history (email);

CREATE INDEX ix_user_login_history_login_at ON user_login_history (login_at);

CREATE INDEX ix_user_login_history_success ON user_login_history (success);

CREATE INDEX ix_user_login_history_user_id ON user_login_history (user_id);

CREATE INDEX ix_user_login_history_user_login ON user_login_history (user_id, login_at);

CREATE TABLE user_placement (
	user_id UUID NOT NULL, 
	has_traded_before BOOLEAN NOT NULL, 
	experience cap0_placement_experience DEFAULT 'never' NOT NULL, 
	placed_level INTEGER NOT NULL, 
	da_xem_tour BOOLEAN DEFAULT 'false' NOT NULL, 
	tour_bantin_done_at TIMESTAMP WITH TIME ZONE, 
	tour_phantich_done_at TIMESTAMP WITH TIME ZONE, 
	tour_bctc_done_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_user_placement PRIMARY KEY (id), 
	CONSTRAINT uq_user_placement_user_id UNIQUE (user_id), 
	CONSTRAINT fk_user_placement_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_user_placement_user_id ON user_placement (user_id);

CREATE TABLE virtual_trading_accounts (
	user_id UUID NOT NULL, 
	status vt_account_status DEFAULT 'active' NOT NULL, 
	initial_cash_vnd BIGINT NOT NULL, 
	cash_available_vnd BIGINT NOT NULL, 
	cash_reserved_vnd BIGINT DEFAULT 0 NOT NULL, 
	cash_pending_vnd BIGINT DEFAULT 0 NOT NULL, 
	scope_type VARCHAR(50), 
	scope_id UUID, 
	activated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	reset_at TIMESTAMP WITH TIME ZONE, 
	frozen_at TIMESTAMP WITH TIME ZONE, 
	frozen_by_user_id UUID, 
	freeze_reason VARCHAR(1000), 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_virtual_trading_accounts PRIMARY KEY (id), 
	CONSTRAINT uq_vt_accounts_user_id UNIQUE (user_id), 
	CONSTRAINT fk_virtual_trading_accounts_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_virtual_trading_accounts_frozen_by_user_id_users FOREIGN KEY(frozen_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_virtual_trading_accounts_user_id ON virtual_trading_accounts (user_id);

CREATE TABLE virtual_trading_configs (
	initial_cash_vnd BIGINT DEFAULT 100000000 NOT NULL, 
	buy_fee_rate_bps INTEGER DEFAULT 15 NOT NULL, 
	sell_fee_rate_bps INTEGER DEFAULT 15 NOT NULL, 
	sell_tax_rate_bps INTEGER DEFAULT 10 NOT NULL, 
	settlement_mode settlement_mode DEFAULT 'T0' NOT NULL, 
	board_lot_size INTEGER DEFAULT 100 NOT NULL, 
	trading_enabled BOOLEAN DEFAULT 'true' NOT NULL, 
	holidays TEXT, 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	created_by UUID, 
	updated_by UUID, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_virtual_trading_configs PRIMARY KEY (id), 
	CONSTRAINT fk_virtual_trading_configs_created_by_users FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE SET NULL, 
	CONSTRAINT fk_virtual_trading_configs_updated_by_users FOREIGN KEY(updated_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE watchlist_items (
	user_id UUID NOT NULL, 
	symbol VARCHAR(20) NOT NULL, 
	sort_order INTEGER DEFAULT '0' NOT NULL, 
	hunt_filter VARCHAR(16), 
	hunt_signal VARCHAR(200), 
	hunt_at TIMESTAMP WITH TIME ZONE, 
	consensus_today INTEGER, 
	consensus_prev INTEGER, 
	consensus_da_cham INTEGER, 
	consensus_at TIMESTAMP WITH TIME ZONE, 
	status VARCHAR(16), 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_watchlist_items PRIMARY KEY (id), 
	CONSTRAINT uq_watchlist_items_user_symbol UNIQUE (user_id, symbol), 
	CONSTRAINT fk_watchlist_items_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_watchlist_items_symbol ON watchlist_items (symbol);

CREATE INDEX ix_watchlist_items_user_id ON watchlist_items (user_id);

CREATE TABLE alert_events (
	user_id UUID NOT NULL, 
	rule_id UUID NOT NULL, 
	symbol VARCHAR(20) NOT NULL, 
	signal_key VARCHAR(40), 
	session_date DATE NOT NULL, 
	fired_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	price NUMERIC(18, 4), 
	delivered BOOLEAN DEFAULT 'false' NOT NULL, 
	delivery_error VARCHAR(300), 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_alert_events PRIMARY KEY (id), 
	CONSTRAINT uq_alert_events_user_rule_symbol_date UNIQUE (user_id, rule_id, symbol, session_date), 
	CONSTRAINT fk_alert_events_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_alert_events_rule_id_user_alert_rules FOREIGN KEY(rule_id) REFERENCES user_alert_rules (id) ON DELETE CASCADE
);

CREATE INDEX ix_alert_events_rule_id ON alert_events (rule_id);

CREATE INDEX ix_alert_events_symbol ON alert_events (symbol);

CREATE INDEX ix_alert_events_user_id ON alert_events (user_id);

CREATE TABLE bot_cash_ledger (
	bot_account_id UUID NOT NULL, 
	execution_id UUID, 
	kind VARCHAR(32) NOT NULL, 
	amount_vnd BIGINT NOT NULL, 
	balance_after_vnd BIGINT NOT NULL, 
	idempotency_key VARCHAR(160) NOT NULL, 
	note VARCHAR(500), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_bot_cash_ledger PRIMARY KEY (id), 
	CONSTRAINT uq_bot_cash_ledger_idempotency UNIQUE (idempotency_key), 
	CONSTRAINT ck_bot_cash_ledger_bot_ledger_balance_non_negative CHECK (balance_after_vnd >= 0), 
	CONSTRAINT fk_bot_cash_ledger_bot_account_id_bot_accounts FOREIGN KEY(bot_account_id) REFERENCES bot_accounts (id) ON DELETE CASCADE
);

CREATE INDEX ix_bot_cash_ledger_bot_account_id ON bot_cash_ledger (bot_account_id);

CREATE UNIQUE INDEX ix_bot_cash_ledger_execution_id ON bot_cash_ledger (execution_id);

CREATE TABLE bot_instances (
	user_id UUID NOT NULL, 
	bot_account_id UUID NOT NULL, 
	strategy_id VARCHAR(64) NOT NULL, 
	strategy_version INTEGER NOT NULL, 
	execution_model VARCHAR(32) NOT NULL, 
	cap6_graduated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	activated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_bot_instances PRIMARY KEY (id), 
	CONSTRAINT uq_bot_instances_user_id UNIQUE (user_id), 
	CONSTRAINT uq_bot_instances_account_id UNIQUE (bot_account_id), 
	CONSTRAINT ck_bot_instances_bot_strategy_version_positive CHECK (strategy_version > 0), 
	CONSTRAINT ck_bot_instances_bot_execution_model_v1 CHECK (execution_model = 'same_session_close'), 
	CONSTRAINT fk_bot_instances_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_bot_instances_bot_account_id_bot_accounts FOREIGN KEY(bot_account_id) REFERENCES bot_accounts (id) ON DELETE CASCADE
);

CREATE INDEX ix_bot_instances_user_id ON bot_instances (user_id);

CREATE TABLE bot_nav_daily (
	bot_account_id UUID NOT NULL, 
	trading_date DATE NOT NULL, 
	cash_vnd BIGINT NOT NULL, 
	market_value_vnd BIGINT, 
	nav_vnd BIGINT, 
	valuation_complete BOOLEAN NOT NULL, 
	vnindex NUMERIC(20, 6), 
	source_refs JSONB DEFAULT '{}'::jsonb NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_bot_nav_daily PRIMARY KEY (id), 
	CONSTRAINT uq_bot_nav_account_date UNIQUE (bot_account_id, trading_date), 
	CONSTRAINT ck_bot_nav_daily_bot_nav_non_negative CHECK (cash_vnd >= 0 AND (market_value_vnd IS NULL OR market_value_vnd >= 0) AND (nav_vnd IS NULL OR nav_vnd >= 0)), 
	CONSTRAINT fk_bot_nav_daily_bot_account_id_bot_accounts FOREIGN KEY(bot_account_id) REFERENCES bot_accounts (id) ON DELETE CASCADE
);

CREATE INDEX ix_bot_nav_daily_bot_account_id ON bot_nav_daily (bot_account_id);

CREATE TABLE bot_positions (
	bot_account_id UUID NOT NULL, 
	symbol VARCHAR(10) NOT NULL, 
	qty_open INTEGER NOT NULL, 
	entry_price_vnd BIGINT NOT NULL, 
	entry_value_vnd BIGINT NOT NULL, 
	entry_fee_vnd BIGINT NOT NULL, 
	amplitude_at_entry_vnd NUMERIC(20, 4) NOT NULL, 
	amplitude_source_ref VARCHAR(500) NOT NULL, 
	stop_loss_vnd NUMERIC(20, 4) NOT NULL, 
	take_profit_vnd NUMERIC(20, 4) NOT NULL, 
	opened_session DATE NOT NULL, 
	opened_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	closed_session DATE, 
	closed_at TIMESTAMP WITH TIME ZONE, 
	buy_execution_id UUID, 
	sell_execution_id UUID, 
	status VARCHAR(16) NOT NULL, 
	filter_ids JSONB DEFAULT '[]'::jsonb NOT NULL, 
	source_refs JSONB DEFAULT '{}'::jsonb NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_bot_positions PRIMARY KEY (id), 
	CONSTRAINT ck_bot_positions_bot_position_qty_non_negative CHECK (qty_open >= 0), 
	CONSTRAINT ck_bot_positions_bot_position_entry_price CHECK (entry_price_vnd > 0), 
	CONSTRAINT ck_bot_positions_bot_position_amplitude CHECK (amplitude_at_entry_vnd > 0), 
	CONSTRAINT ck_bot_positions_bot_position_stop CHECK (stop_loss_vnd > 0 AND stop_loss_vnd < entry_price_vnd), 
	CONSTRAINT ck_bot_positions_bot_position_take_profit CHECK (take_profit_vnd > entry_price_vnd), 
	CONSTRAINT ck_bot_positions_bot_position_status CHECK (status IN ('open', 'closed')), 
	CONSTRAINT fk_bot_positions_bot_account_id_bot_accounts FOREIGN KEY(bot_account_id) REFERENCES bot_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT uq_bot_positions_buy_execution_id UNIQUE (buy_execution_id), 
	CONSTRAINT uq_bot_positions_sell_execution_id UNIQUE (sell_execution_id)
);

CREATE INDEX ix_bot_positions_bot_account_id ON bot_positions (bot_account_id);

CREATE INDEX ix_bot_positions_symbol ON bot_positions (symbol);

CREATE UNIQUE INDEX uq_bot_positions_open_symbol ON bot_positions (bot_account_id, symbol) WHERE status = 'open';

CREATE TABLE bot_run_receipts (
	user_id UUID NOT NULL, 
	trading_date DATE NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	issues JSONB DEFAULT '[]'::jsonb NOT NULL, 
	bot_account_id UUID, 
	strategy_id VARCHAR(64), 
	strategy_version INTEGER, 
	execution_model VARCHAR(32), 
	source_snapshot_hash VARCHAR(64), 
	rule_snapshot JSONB, 
	rule_hash VARCHAR(64), 
	nav_basis_vnd BIGINT, 
	blocked_symbols_at_start JSONB DEFAULT '[]'::jsonb NOT NULL, 
	buy_count INTEGER DEFAULT 0 NOT NULL, 
	sell_count INTEGER DEFAULT 0 NOT NULL, 
	reconciled_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_bot_run_receipts PRIMARY KEY (id), 
	CONSTRAINT uq_bot_run_receipts_user_id UNIQUE (user_id, trading_date), 
	CONSTRAINT uq_bot_run_account_date UNIQUE (bot_account_id, trading_date), 
	CONSTRAINT ck_bot_run_receipts_status CHECK (status IN ('running', 'succeeded', 'failed')), 
	CONSTRAINT ck_bot_run_receipts_completed_at CHECK (status = 'running' OR completed_at IS NOT NULL), 
	CONSTRAINT ck_bot_run_receipts_bot_run_counts CHECK (buy_count >= 0 AND sell_count >= 0), 
	CONSTRAINT fk_bot_run_receipts_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_bot_run_receipts_bot_account_id_bot_accounts FOREIGN KEY(bot_account_id) REFERENCES bot_accounts (id) ON DELETE CASCADE
);

CREATE INDEX ix_bot_run_receipts_bot_account_id ON bot_run_receipts (bot_account_id);

CREATE INDEX ix_bot_run_receipts_user_id ON bot_run_receipts (user_id);

CREATE TABLE episodes (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	course_id UUID NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	description TEXT, 
	content_type VARCHAR(20) NOT NULL, 
	file_url VARCHAR(500), 
	markdown_body TEXT, 
	duration_seconds INTEGER, 
	file_size_bytes BIGINT, 
	sort_order INTEGER NOT NULL, 
	is_published BOOLEAN DEFAULT true NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_episodes PRIMARY KEY (id), 
	CONSTRAINT ck_episodes_ck_episodes_payload_shape CHECK ((content_type = 'text' AND markdown_body IS NOT NULL AND file_url IS NULL) OR (content_type IN ('pdf','video') AND markdown_body IS NULL)), 
	CONSTRAINT uq_episodes_course_sort UNIQUE (course_id, sort_order), 
	CONSTRAINT fk_episodes_course_id_courses FOREIGN KEY(course_id) REFERENCES courses (id) ON DELETE CASCADE
);

CREATE INDEX ix_episodes_course_id ON episodes (course_id);

CREATE INDEX ix_episodes_course_sort ON episodes (course_id, sort_order);

CREATE TABLE journey_assessments (
	user_id UUID NOT NULL, 
	dataset_id UUID NOT NULL, 
	symbol VARCHAR(10) NOT NULL, 
	trading_date DATE NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	answers JSONB NOT NULL, 
	source VARCHAR(24) DEFAULT 'learning' NOT NULL, 
	mode VARCHAR(24) DEFAULT 'thuc_chien' NOT NULL, 
	record_status VARCHAR(24) DEFAULT 'valid' NOT NULL, 
	proof_version VARCHAR(32) DEFAULT 'commit_then_reveal_v1' NOT NULL, 
	revealed_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_journey_assessments PRIMARY KEY (id), 
	CONSTRAINT uq_journey_assessments_user_id UNIQUE (user_id, symbol, trading_date), 
	CONSTRAINT fk_journey_assessments_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_journey_assessments_dataset_id_journey_reading_datasets FOREIGN KEY(dataset_id) REFERENCES journey_reading_datasets (id)
);

CREATE INDEX ix_journey_assessments_user_id ON journey_assessments (user_id);

CREATE TABLE portfolio_reports (
	account_id UUID NOT NULL, 
	session_date DATE NOT NULL, 
	period_number INTEGER DEFAULT 1 NOT NULL, 
	mode VARCHAR(20) NOT NULL, 
	analysis_json JSONB NOT NULL, 
	narrative_json JSONB, 
	scores JSONB, 
	recommended_actions JSONB, 
	watch_conditions JSONB, 
	holdings_snapshot JSONB, 
	model_used VARCHAR(50), 
	generation_time_ms INTEGER, 
	valid BOOLEAN DEFAULT 'true' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_portfolio_reports PRIMARY KEY (id), 
	CONSTRAINT uq_portfolio_reports_account_date UNIQUE (account_id, session_date), 
	CONSTRAINT fk_portfolio_reports_account_id_virtual_trading_accounts FOREIGN KEY(account_id) REFERENCES virtual_trading_accounts (id) ON DELETE CASCADE
);

CREATE INDEX ix_portfolio_reports_account_date ON portfolio_reports (account_id, session_date);

CREATE INDEX ix_portfolio_reports_account_id ON portfolio_reports (account_id);

CREATE INDEX ix_portfolio_reports_session_date ON portfolio_reports (session_date);

CREATE TABLE sepay_ipn_logs (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	received_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	secret_key_valid BOOLEAN NOT NULL, 
	raw_body JSONB, 
	raw_headers JSONB, 
	result_status VARCHAR(60), 
	matched_order_id UUID, 
	sepay_transaction_id VARCHAR(200), 
	error_message TEXT, 
	CONSTRAINT pk_sepay_ipn_logs PRIMARY KEY (id), 
	CONSTRAINT fk_sepay_ipn_logs_matched_order_id_premium_payment_orders FOREIGN KEY(matched_order_id) REFERENCES premium_payment_orders (id) ON DELETE SET NULL
);

CREATE INDEX ix_sepay_ipn_logs_matched_order_id ON sepay_ipn_logs (matched_order_id);

CREATE INDEX ix_sepay_ipn_logs_received_at ON sepay_ipn_logs (received_at);

CREATE INDEX ix_sepay_ipn_logs_received_status ON sepay_ipn_logs (received_at, result_status);

CREATE INDEX ix_sepay_ipn_logs_result_status ON sepay_ipn_logs (result_status);

CREATE INDEX ix_sepay_ipn_logs_secret_key_valid ON sepay_ipn_logs (secret_key_valid);

CREATE INDEX ix_sepay_ipn_logs_sepay_transaction_id ON sepay_ipn_logs (sepay_transaction_id);

CREATE TABLE virtual_cash_ledger (
	account_id UUID NOT NULL, 
	amount_vnd BIGINT NOT NULL, 
	balance_after_vnd BIGINT NOT NULL, 
	kind VARCHAR(50) NOT NULL, 
	reference_type VARCHAR(50), 
	reference_id UUID, 
	note VARCHAR(500), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_virtual_cash_ledger PRIMARY KEY (id), 
	CONSTRAINT fk_virtual_cash_ledger_account_id_virtual_trading_accounts FOREIGN KEY(account_id) REFERENCES virtual_trading_accounts (id) ON DELETE CASCADE
);

CREATE INDEX ix_virtual_cash_ledger_account_id ON virtual_cash_ledger (account_id);

CREATE TABLE virtual_orders (
	account_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	symbol VARCHAR(10) NOT NULL, 
	mode VARCHAR DEFAULT 'thuc_chien' NOT NULL, 
	side vt_order_side NOT NULL, 
	order_type vt_order_type NOT NULL, 
	status vt_order_status DEFAULT 'pending' NOT NULL, 
	quantity INTEGER NOT NULL, 
	limit_price_vnd BIGINT, 
	reserved_cash_vnd BIGINT DEFAULT 0 NOT NULL, 
	reserved_quantity INTEGER DEFAULT 0 NOT NULL, 
	filled_price_vnd BIGINT, 
	gross_amount_vnd BIGINT, 
	fee_vnd BIGINT, 
	tax_vnd BIGINT, 
	net_amount_vnd BIGINT, 
	trading_date DATE NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	rejection_reason VARCHAR(500), 
	cancel_reason VARCHAR(500), 
	config_snapshot TEXT, 
	exit_snapshot_at TIMESTAMP WITH TIME ZONE, 
	position_quantity_before_fill INTEGER, 
	position_quantity_after_fill INTEGER, 
	exit_matched_buy_order_id UUID, 
	exit_original_stop_vnd BIGINT, 
	exit_original_take_profit_vnd BIGINT, 
	exit_dynamic_stop_vnd BIGINT, 
	exit_dynamic_stop_set_at TIMESTAMP WITH TIME ZONE, 
	exit_avg_cost_vnd BIGINT, 
	exit_plan_activated_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_virtual_orders PRIMARY KEY (id), 
	CONSTRAINT fk_virtual_orders_account_id_virtual_trading_accounts FOREIGN KEY(account_id) REFERENCES virtual_trading_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_virtual_orders_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_virtual_orders_exit_matched_buy_order_id_virtual_orders FOREIGN KEY(exit_matched_buy_order_id) REFERENCES virtual_orders (id) ON DELETE SET NULL
);

CREATE INDEX ix_virtual_orders_account_id ON virtual_orders (account_id);

CREATE INDEX ix_virtual_orders_symbol ON virtual_orders (symbol);

CREATE INDEX ix_virtual_orders_user_id ON virtual_orders (user_id);

CREATE TABLE bot_executions (
	bot_run_id UUID NOT NULL, 
	bot_account_id UUID NOT NULL, 
	position_id UUID NOT NULL, 
	symbol VARCHAR(10) NOT NULL, 
	side VARCHAR(8) NOT NULL, 
	qty INTEGER NOT NULL, 
	price_vnd BIGINT NOT NULL, 
	signal_session DATE NOT NULL, 
	price_session DATE NOT NULL, 
	trading_date DATE NOT NULL, 
	executed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	gross_value_vnd BIGINT NOT NULL, 
	fee_vnd BIGINT NOT NULL, 
	tax_vnd BIGINT NOT NULL, 
	net_cash_delta_vnd BIGINT NOT NULL, 
	execution_model VARCHAR(32) NOT NULL, 
	idempotency_key VARCHAR(160) NOT NULL, 
	filter_ids JSONB DEFAULT '[]'::jsonb NOT NULL, 
	supporting_count INTEGER, 
	layer_snapshot JSONB DEFAULT '{}'::jsonb NOT NULL, 
	reason VARCHAR(1000) NOT NULL, 
	source_snapshot_id VARCHAR(64) NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_bot_executions PRIMARY KEY (id), 
	CONSTRAINT uq_bot_execution_idempotency UNIQUE (idempotency_key), 
	CONSTRAINT ck_bot_executions_bot_execution_side CHECK (side IN ('buy', 'sell')), 
	CONSTRAINT ck_bot_executions_bot_execution_qty CHECK (qty > 0), 
	CONSTRAINT ck_bot_executions_bot_execution_price CHECK (price_vnd > 0), 
	CONSTRAINT ck_bot_executions_bot_execution_same_session CHECK (signal_session = price_session AND price_session = trading_date), 
	CONSTRAINT ck_bot_executions_bot_execution_model CHECK (execution_model = 'same_session_close'), 
	CONSTRAINT fk_bot_executions_bot_run_id_bot_run_receipts FOREIGN KEY(bot_run_id) REFERENCES bot_run_receipts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_bot_executions_bot_account_id_bot_accounts FOREIGN KEY(bot_account_id) REFERENCES bot_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_bot_executions_position_id_bot_positions FOREIGN KEY(position_id) REFERENCES bot_positions (id) ON DELETE RESTRICT
);

CREATE INDEX ix_bot_executions_bot_account_id ON bot_executions (bot_account_id);

CREATE INDEX ix_bot_executions_bot_run_id ON bot_executions (bot_run_id);

CREATE INDEX ix_bot_executions_position_id ON bot_executions (position_id);

CREATE INDEX ix_bot_executions_symbol ON bot_executions (symbol);

CREATE TABLE bot_market_snapshots (
	bot_run_id UUID NOT NULL, 
	trading_date DATE NOT NULL, 
	data_version VARCHAR(128) NOT NULL, 
	observed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	close_is_official BOOLEAN NOT NULL, 
	buy_inputs_complete BOOLEAN NOT NULL, 
	snapshot_hash VARCHAR(64) NOT NULL, 
	payload JSONB NOT NULL, 
	source_refs JSONB DEFAULT '{}'::jsonb NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_bot_market_snapshots PRIMARY KEY (id), 
	CONSTRAINT uq_bot_snapshot_run UNIQUE (bot_run_id), 
	CONSTRAINT fk_bot_market_snapshots_bot_run_id_bot_run_receipts FOREIGN KEY(bot_run_id) REFERENCES bot_run_receipts (id) ON DELETE CASCADE
);

CREATE INDEX ix_bot_market_snapshots_trading_date ON bot_market_snapshots (trading_date);

CREATE TABLE cap0_order_kehoach (
	order_id UUID NOT NULL, 
	ly_do_doi_thuong cap0_ly_do_doi_thuong NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap0_order_kehoach PRIMARY KEY (id), 
	CONSTRAINT fk_cap0_order_kehoach_order_id_virtual_orders FOREIGN KEY(order_id) REFERENCES virtual_orders (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_cap0_order_kehoach_order_id ON cap0_order_kehoach (order_id);

CREATE TABLE cap2_alert_events (
	user_id UUID NOT NULL, 
	alert_type VARCHAR(20) NOT NULL, 
	symbol VARCHAR(10) NOT NULL, 
	session_date DATE NOT NULL, 
	trigger_key VARCHAR(180) NOT NULL, 
	source_order_id UUID, 
	source_plan_order_id UUID, 
	observed_price_vnd BIGINT NOT NULL, 
	threshold_price_vnd BIGINT, 
	loss_pct FLOAT, 
	position_quantity INTEGER, 
	position_avg_cost_vnd BIGINT, 
	plan_started_at TIMESTAMP WITH TIME ZONE, 
	intended_quantity INTEGER, 
	intended_order_type VARCHAR(10), 
	intended_limit_price_vnd BIGINT, 
	violation_confirmed_at TIMESTAMP WITH TIME ZONE, 
	official_close_session_date DATE, 
	official_close_at TIMESTAMP WITH TIME ZONE, 
	official_close_source VARCHAR(80), 
	breach_session_no INTEGER DEFAULT '1' NOT NULL, 
	status VARCHAR(16) DEFAULT 'pending' NOT NULL, 
	suppression_reason VARCHAR(40), 
	escalation VARCHAR(20), 
	impression_count INTEGER DEFAULT '0' NOT NULL, 
	first_shown_at TIMESTAMP WITH TIME ZONE, 
	last_shown_at TIMESTAMP WITH TIME ZONE, 
	action VARCHAR(20), 
	acted_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap2_alert_events PRIMARY KEY (id), 
	CONSTRAINT uq_cap2_alert_events_user_type_trigger UNIQUE (user_id, alert_type, trigger_key), 
	CONSTRAINT ck_cap2_alert_events_cap2_alert_event_type CHECK (alert_type IN ('nhoi_lenh', 'cham_cat_lo')), 
	CONSTRAINT ck_cap2_alert_events_cap2_alert_event_status CHECK (status IN ('pending', 'shown', 'suppressed', 'acted')), 
	CONSTRAINT ck_cap2_alert_events_cap2_alert_event_escalation CHECK (escalation IS NULL OR escalation IN ('normal', 'delay_5s', 'type_phrase')), 
	CONSTRAINT ck_cap2_alert_events_cap2_alert_event_action CHECK (action IS NULL OR action IN ('cancel_buy', 'proceed_buy', 'sell_ato', 'hold', 'position_closed')), 
	CONSTRAINT ck_cap2_alert_events_cap2_alert_event_impressions_nonnegative CHECK (impression_count >= 0), 
	CONSTRAINT ck_cap2_alert_events_cap2_alert_event_breach_session_positive CHECK (breach_session_no >= 1), 
	CONSTRAINT ck_cap2_alert_events_cap2_alert_event_draft_shape CHECK ((intended_quantity IS NULL AND intended_order_type IS NULL AND intended_limit_price_vnd IS NULL) OR (intended_quantity IS NOT NULL AND intended_quantity > 0 AND intended_order_type IS NOT NULL AND ((intended_order_type = 'market' AND intended_limit_price_vnd IS NULL) OR (intended_order_type = 'limit' AND intended_limit_price_vnd IS NOT NULL AND intended_limit_price_vnd > 0)))), 
	CONSTRAINT fk_cap2_alert_events_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_cap2_alert_events_source_order_id_virtual_orders FOREIGN KEY(source_order_id) REFERENCES virtual_orders (id) ON DELETE SET NULL, 
	CONSTRAINT fk_cap2_alert_events_source_plan_order_id_virtual_orders FOREIGN KEY(source_plan_order_id) REFERENCES virtual_orders (id) ON DELETE SET NULL
);

CREATE INDEX ix_cap2_alert_events_session_date ON cap2_alert_events (session_date);

CREATE INDEX ix_cap2_alert_events_symbol ON cap2_alert_events (symbol);

CREATE INDEX ix_cap2_alert_events_user_id ON cap2_alert_events (user_id);

CREATE INDEX ix_cap2_alert_events_user_session_status ON cap2_alert_events (user_id, session_date, status);

CREATE INDEX ix_cap2_alert_events_user_type_acted ON cap2_alert_events (user_id, alert_type, acted_at);

CREATE TABLE cap8_exits (
	user_id UUID NOT NULL, 
	account_id UUID NOT NULL, 
	symbol VARCHAR(10) NOT NULL, 
	matched_buy_order_id UUID, 
	sell_order_id UUID NOT NULL, 
	exited_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	quantity INTEGER NOT NULL, 
	filled_price_vnd BIGINT NOT NULL, 
	remaining_position_pct FLOAT NOT NULL, 
	exit_method VARCHAR(16) NOT NULL, 
	original_stop_vnd BIGINT, 
	original_take_profit_vnd BIGINT, 
	effective_stop_vnd BIGINT, 
	dung_ke_hoach BOOLEAN DEFAULT false NOT NULL, 
	ban_cam_xuc BOOLEAN DEFAULT false NOT NULL, 
	classification_reason VARCHAR(128) NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap8_exits PRIMARY KEY (id), 
	CONSTRAINT uq_cap8_exits_sell_order_id UNIQUE (sell_order_id), 
	CONSTRAINT fk_cap8_exits_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_cap8_exits_account_id_virtual_trading_accounts FOREIGN KEY(account_id) REFERENCES virtual_trading_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_cap8_exits_matched_buy_order_id_virtual_orders FOREIGN KEY(matched_buy_order_id) REFERENCES virtual_orders (id) ON DELETE SET NULL, 
	CONSTRAINT fk_cap8_exits_sell_order_id_virtual_orders FOREIGN KEY(sell_order_id) REFERENCES virtual_orders (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap8_exits_account_id ON cap8_exits (account_id);

CREATE INDEX ix_cap8_exits_symbol ON cap8_exits (symbol);

CREATE INDEX ix_cap8_exits_user_id ON cap8_exits (user_id);

CREATE TABLE episode_progress (
	user_id UUID NOT NULL, 
	episode_id UUID NOT NULL, 
	course_id UUID NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	last_position_seconds INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_episode_progress PRIMARY KEY (user_id, episode_id), 
	CONSTRAINT fk_episode_progress_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_episode_progress_episode_id_episodes FOREIGN KEY(episode_id) REFERENCES episodes (id) ON DELETE CASCADE, 
	CONSTRAINT fk_episode_progress_course_id_courses FOREIGN KEY(course_id) REFERENCES courses (id) ON DELETE CASCADE
);

CREATE INDEX ix_ep_progress_user_course ON episode_progress (user_id, course_id, completed_at);

CREATE INDEX ix_episode_progress_course_id ON episode_progress (course_id);

CREATE TABLE order_kehoach (
	order_id UUID NOT NULL, 
	"lyDo" cap1_ly_do NOT NULL, 
	"trangThai_luc_dat" cap1_trang_thai_luc_dat NOT NULL, 
	vung_mua BIGINT NOT NULL, 
	co_bam_doc_chi_tiet BOOLEAN DEFAULT 'false' NOT NULL, 
	snapshot_lop_du_lieu JSONB, 
	phuong_phap_sl_tp cap2_phuong_phap_sl_tp, 
	cat_lo BIGINT, 
	chot_loi BIGINT, 
	khau_vi cap3_khau_vi_rui_ro, 
	muc_tu_tin INTEGER, 
	cach_khoi_luong cap3_cach_khoi_luong, 
	khoi_luong INTEGER, 
	pct_von FLOAT, 
	doc_5_lop JSONB, 
	ai_5_lop JSONB, 
	so_lop_dong_thuan INTEGER, 
	so_lop_khac_ai INTEGER, 
	from_watchlist BOOLEAN, 
	hunt_filter VARCHAR(16), 
	cap5_entry_snapshot_at TIMESTAMP WITH TIME ZONE, 
	hunt_signal_at_entry VARCHAR(200), 
	hunt_first_hunted_at_entry TIMESTAMP WITH TIME ZONE, 
	hunt_sessions_at_entry INTEGER, 
	consensus_at_entry INTEGER, 
	consensus_scored_at_entry INTEGER, 
	consensus_captured_at_entry TIMESTAMP WITH TIME ZONE, 
	had_conflict BOOLEAN, 
	conflict_level VARCHAR(8), 
	had_veto BOOLEAN, 
	veto_layers JSONB, 
	support_layers JSONB, 
	opposing_layers JSONB, 
	neutral_layers JSONB, 
	conflict_snapshot_session_date DATE, 
	conflict_snapshot_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_order_kehoach PRIMARY KEY (id), 
	CONSTRAINT ck_order_kehoach_ck_order_kehoach_consensus_at_entry_range CHECK (consensus_at_entry IS NULL OR consensus_at_entry BETWEEN 0 AND 5), 
	CONSTRAINT ck_order_kehoach_ck_order_kehoach_consensus_scored_at_e_9c1f CHECK (consensus_scored_at_entry IS NULL OR consensus_scored_at_entry BETWEEN 0 AND 5), 
	CONSTRAINT ck_order_kehoach_ck_order_kehoach_consensus_entry_order CHECK (consensus_at_entry IS NULL OR consensus_scored_at_entry IS NULL OR consensus_at_entry <= consensus_scored_at_entry), 
	CONSTRAINT fk_order_kehoach_order_id_virtual_orders FOREIGN KEY(order_id) REFERENCES virtual_orders (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_order_kehoach_order_id ON order_kehoach (order_id);

CREATE TABLE order_ketso (
	order_id UUID NOT NULL, 
	gia_ra BIGINT NOT NULL, 
	so_phien_giu INTEGER NOT NULL, 
	so_ngay_lich INTEGER NOT NULL, 
	pnl_pct FLOAT NOT NULL, 
	pnl_vnd BIGINT NOT NULL, 
	cam_xuc cap1_cam_xuc, 
	closed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	"cham_SL_cuoi_phien" BOOLEAN DEFAULT 'false' NOT NULL, 
	"cham_SL_cat_dung_phien_ke" BOOLEAN DEFAULT 'false' NOT NULL, 
	"cham_SL_khong_cat" BOOLEAN DEFAULT 'false' NOT NULL, 
	"giu_cham_SL_bao_nhieu_phien" INTEGER DEFAULT '0', 
	"cham_TP_giu_lam_hut" BOOLEAN DEFAULT 'false' NOT NULL, 
	ban_som_khi_lo_nhe BOOLEAN DEFAULT 'false' NOT NULL, 
	nhoi_lenh_khi_lo BOOLEAN DEFAULT 'false' NOT NULL, 
	ghi_chu_nhin_lai VARCHAR(2000), 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_order_ketso PRIMARY KEY (id), 
	CONSTRAINT fk_order_ketso_order_id_virtual_orders FOREIGN KEY(order_id) REFERENCES virtual_orders (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_order_ketso_order_id ON order_ketso (order_id);

CREATE TABLE virtual_positions (
	account_id UUID NOT NULL, 
	symbol VARCHAR(10) NOT NULL, 
	quantity_total INTEGER DEFAULT 0 NOT NULL, 
	quantity_sellable INTEGER DEFAULT 0 NOT NULL, 
	quantity_pending INTEGER DEFAULT 0 NOT NULL, 
	quantity_reserved INTEGER DEFAULT 0 NOT NULL, 
	avg_cost_vnd BIGINT DEFAULT 0 NOT NULL, 
	active_plan_buy_order_id UUID, 
	active_original_stop_vnd BIGINT, 
	active_original_take_profit_vnd BIGINT, 
	active_dynamic_stop_vnd BIGINT, 
	active_dynamic_stop_set_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_virtual_positions PRIMARY KEY (id), 
	CONSTRAINT uq_vt_positions_account_symbol UNIQUE (account_id, symbol), 
	CONSTRAINT fk_virtual_positions_account_id_virtual_trading_accounts FOREIGN KEY(account_id) REFERENCES virtual_trading_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_virtual_positions_active_plan_buy_order_id_virtual_orders FOREIGN KEY(active_plan_buy_order_id) REFERENCES virtual_orders (id) ON DELETE SET NULL
);

CREATE INDEX ix_virtual_positions_account_id ON virtual_positions (account_id);

CREATE INDEX ix_virtual_positions_active_plan_buy_order_id ON virtual_positions (active_plan_buy_order_id);

CREATE TABLE virtual_trades (
	order_id UUID NOT NULL, 
	account_id UUID NOT NULL, 
	symbol VARCHAR(10) NOT NULL, 
	side vt_order_side NOT NULL, 
	quantity INTEGER NOT NULL, 
	price_vnd BIGINT NOT NULL, 
	gross_amount_vnd BIGINT NOT NULL, 
	fee_vnd BIGINT NOT NULL, 
	tax_vnd BIGINT NOT NULL, 
	net_amount_vnd BIGINT NOT NULL, 
	price_source VARCHAR(50) NOT NULL, 
	price_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	traded_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_virtual_trades PRIMARY KEY (id), 
	CONSTRAINT fk_virtual_trades_order_id_virtual_orders FOREIGN KEY(order_id) REFERENCES virtual_orders (id) ON DELETE CASCADE, 
	CONSTRAINT fk_virtual_trades_account_id_virtual_trading_accounts FOREIGN KEY(account_id) REFERENCES virtual_trading_accounts (id) ON DELETE CASCADE
);

CREATE INDEX ix_virtual_trades_account_id ON virtual_trades (account_id);

CREATE INDEX ix_virtual_trades_order_id ON virtual_trades (order_id);

CREATE TABLE bot_decisions (
	bot_run_id UUID NOT NULL, 
	idempotency_key VARCHAR(180) NOT NULL, 
	symbol VARCHAR(10), 
	action VARCHAR(8) NOT NULL, 
	reason_code VARCHAR(64) NOT NULL, 
	reason VARCHAR(1000) NOT NULL, 
	filter_ids JSONB DEFAULT '[]'::jsonb NOT NULL, 
	rank_tuple JSONB, 
	data_refs JSONB DEFAULT '{}'::jsonb NOT NULL, 
	budget_vnd BIGINT, 
	proposed_qty INTEGER, 
	threshold_vnd NUMERIC(20, 4), 
	execution_id UUID, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_bot_decisions PRIMARY KEY (id), 
	CONSTRAINT uq_bot_decision_idempotency UNIQUE (idempotency_key), 
	CONSTRAINT ck_bot_decisions_bot_decision_action CHECK (action IN ('buy', 'sell', 'hold', 'skip')), 
	CONSTRAINT fk_bot_decisions_bot_run_id_bot_run_receipts FOREIGN KEY(bot_run_id) REFERENCES bot_run_receipts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_bot_decisions_execution_id_bot_executions FOREIGN KEY(execution_id) REFERENCES bot_executions (id) ON DELETE SET NULL
);

CREATE INDEX ix_bot_decisions_bot_run_id ON bot_decisions (bot_run_id);

CREATE INDEX ix_bot_decisions_symbol ON bot_decisions (symbol);

CREATE TABLE cap2_alert_impressions (
	event_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	session_date DATE NOT NULL, 
	escalation VARCHAR(20) NOT NULL, 
	shown_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_cap2_alert_impressions PRIMARY KEY (id), 
	CONSTRAINT uq_cap2_alert_impressions_event_date UNIQUE (event_id, session_date), 
	CONSTRAINT ck_cap2_alert_impressions_cap2_alert_impression_escalation CHECK (escalation IN ('normal', 'delay_5s', 'type_phrase')), 
	CONSTRAINT fk_cap2_alert_impressions_event_id_cap2_alert_events FOREIGN KEY(event_id) REFERENCES cap2_alert_events (id) ON DELETE CASCADE, 
	CONSTRAINT fk_cap2_alert_impressions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_cap2_alert_impressions_event_id ON cap2_alert_impressions (event_id);

CREATE INDEX ix_cap2_alert_impressions_user_id ON cap2_alert_impressions (user_id);

CREATE INDEX ix_cap2_alert_impressions_user_session ON cap2_alert_impressions (user_id, session_date);

CREATE TABLE virtual_settlements (
	account_id UUID NOT NULL, 
	trade_id UUID NOT NULL, 
	kind vt_settlement_kind NOT NULL, 
	amount BIGINT NOT NULL, 
	symbol VARCHAR(10), 
	due_date DATE NOT NULL, 
	status vt_settlement_status DEFAULT 'pending' NOT NULL, 
	settled_at TIMESTAMP WITH TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_virtual_settlements PRIMARY KEY (id), 
	CONSTRAINT fk_virtual_settlements_account_id_virtual_trading_accounts FOREIGN KEY(account_id) REFERENCES virtual_trading_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_virtual_settlements_trade_id_virtual_trades FOREIGN KEY(trade_id) REFERENCES virtual_trades (id) ON DELETE CASCADE
);

CREATE INDEX ix_virtual_settlements_account_id ON virtual_settlements (account_id);

CREATE INDEX ix_virtual_settlements_due_date ON virtual_settlements (due_date);
