"""Immutable pre-reveal evidence and journey identity UI state.

Revision ID: c8d9e0f1a2b3
Revises: b7c8d9e0f1a2
"""

from alembic import op
import sqlalchemy as sa

revision = "c8d9e0f1a2b3"
down_revision = "b7c8d9e0f1a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_mascot_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("mascot_rules_version", sa.Integer(), nullable=False),
        sa.Column("assignment_status", sa.String(length=32), nullable=False),
        sa.Column("mascot_id", sa.String(length=24), nullable=True),
        sa.Column("dominant_layer", sa.String(length=24), nullable=True),
        sa.Column("assignment_basis", sa.String(length=32), nullable=True),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_pair_count", sa.Integer(), nullable=False),
        sa.Column("match_counts", sa.JSON(), nullable=False),
        sa.Column("tied_layers", sa.JSON(), nullable=False),
        sa.Column("selected_assessment_refs", sa.JSON(), nullable=False),
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("excluded_records_summary", sa.JSON(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("valid_pair_count >= 0", name=op.f("ck_bot_mascot_profiles_valid_pair_count")),
        sa.CheckConstraint("mascot_rules_version > 0", name=op.f("ck_bot_mascot_profiles_rules_version")),
        sa.CheckConstraint(
            "assignment_status IN ('assigned', 'pending_data_repair')",
            name=op.f("ck_bot_mascot_profiles_assignment_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bot_mascot_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_mascot_profiles")),
        sa.UniqueConstraint("user_id", "mascot_rules_version", name=op.f("uq_bot_mascot_profiles_user_id")),
    )
    op.create_index(op.f("ix_bot_mascot_profiles_user_id"), "bot_mascot_profiles", ["user_id"], unique=False)
    op.create_table(
        "bot_run_receipts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issues", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name=op.f("ck_bot_run_receipts_status")),
        sa.CheckConstraint(
            "status = 'running' OR completed_at IS NOT NULL", name=op.f("ck_bot_run_receipts_completed_at")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bot_run_receipts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_run_receipts")),
        sa.UniqueConstraint("user_id", "trading_date", name=op.f("uq_bot_run_receipts_user_id")),
    )
    op.create_index(op.f("ix_bot_run_receipts_user_id"), "bot_run_receipts", ["user_id"], unique=False)
    op.create_table(
        "journey_identity_ui",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("last_seen_egg_level", sa.Integer(), nullable=True),
        sa.Column("last_seen_egg_level_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("egg_hatch_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mascot_reveal_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mascot_greeted_local_date", sa.Date(), nullable=True),
        sa.Column("last_animated_bot_run_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "last_seen_egg_level IS NULL OR last_seen_egg_level BETWEEN 0 AND 6",
            name=op.f("ck_journey_identity_ui_egg_level"),
        ),
        sa.CheckConstraint(
            "mascot_reveal_seen_at IS NULL OR egg_hatch_seen_at IS NOT NULL",
            name=op.f("ck_journey_identity_ui_hatch_before_reveal"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_journey_identity_ui_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_journey_identity_ui")),
    )
    op.create_table(
        "journey_reading_datasets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_journey_reading_datasets_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journey_reading_datasets")),
    )
    op.create_index(op.f("ix_journey_reading_datasets_user_id"), "journey_reading_datasets", ["user_id"], unique=False)
    op.create_table(
        "journey_assessments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("record_status", sa.String(length=24), nullable=False),
        sa.Column("proof_version", sa.String(length=32), nullable=False),
        sa.Column("revealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["journey_reading_datasets.id"],
            name=op.f("fk_journey_assessments_dataset_id_journey_reading_datasets"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_journey_assessments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journey_assessments")),
        sa.UniqueConstraint("user_id", "symbol", "trading_date", name=op.f("uq_journey_assessments_user_id")),
    )
    op.create_index(op.f("ix_journey_assessments_user_id"), "journey_assessments", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journey_assessments_user_id"), table_name="journey_assessments")
    op.drop_table("journey_assessments")
    op.drop_index(op.f("ix_journey_reading_datasets_user_id"), table_name="journey_reading_datasets")
    op.drop_table("journey_reading_datasets")
    op.drop_table("journey_identity_ui")
    op.drop_index(op.f("ix_bot_run_receipts_user_id"), table_name="bot_run_receipts")
    op.drop_table("bot_run_receipts")
    op.drop_index(op.f("ix_bot_mascot_profiles_user_id"), table_name="bot_mascot_profiles")
    op.drop_table("bot_mascot_profiles")
    # ### end Alembic commands ###
