"""add_ipn_logs_and_billing_snapshots

Revision ID: faeec52ea69f
Revises: b869a2a74654
Create Date: 2026-04-23 09:16:04.922156
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faeec52ea69f'
down_revision: Union[str, None] = 'b869a2a74654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_ipn_logs',
    sa.Column('payment_order_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['payment_order_id'], ['payment_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_ipn_logs_invoice_number'), 'payment_ipn_logs', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_payment_ipn_logs_payment_order_id'), 'payment_ipn_logs', ['payment_order_id'], unique=False)
    op.add_column('payment_orders', sa.Column('plan_snapshot_code', sa.String(length=50), nullable=True))
    op.add_column('payment_orders', sa.Column('plan_snapshot_name', sa.String(length=100), nullable=True))
    op.add_column('payment_orders', sa.Column('plan_snapshot_price', sa.Integer(), nullable=True))
    op.add_column('payment_orders', sa.Column('plan_snapshot_duration', sa.Integer(), nullable=True))
    op.add_column('payment_orders', sa.Column('plan_snapshot_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_orders', 'plan_snapshot_features')
    op.drop_column('payment_orders', 'plan_snapshot_duration')
    op.drop_column('payment_orders', 'plan_snapshot_price')
    op.drop_column('payment_orders', 'plan_snapshot_name')
    op.drop_column('payment_orders', 'plan_snapshot_code')
    op.drop_index(op.f('ix_payment_ipn_logs_payment_order_id'), table_name='payment_ipn_logs')
    op.drop_index(op.f('ix_payment_ipn_logs_invoice_number'), table_name='payment_ipn_logs')
    op.drop_table('payment_ipn_logs')
    # ### end Alembic commands ###
