"""add_premium_tables

Revision ID: fb7a64f07299
Revises: 488c85bb0b6a
Create Date: 2026-04-24 21:18:25.632541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7a64f07299'
down_revision: Union[str, None] = '488c85bb0b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premium_plans',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_vnd', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_premium_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_premium_plans_code'))
    )
    op.create_table('premium_payment_orders',
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('amount_vnd', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='VND', nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'cancelled', name='payment_order_status'), server_default='pending', nullable=False),
    sa.Column('sepay_transaction_id', sa.String(length=200), nullable=True),
    sa.Column('raw_ipn', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grant_type', sa.String(length=20), nullable=True),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('grant_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('fk_premium_payment_orders_granted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['premium_plans.id'], name=op.f('fk_premium_payment_orders_plan_id_premium_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_premium_payment_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_premium_payment_orders')),
    sa.UniqueConstraint('sepay_transaction_id', name=op.f('uq_premium_payment_orders_sepay_transaction_id'))
    )
    op.create_index(op.f('ix_premium_payment_orders_invoice_number'), 'premium_payment_orders', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_premium_payment_orders_user_id'), 'premium_payment_orders', ['user_id'], unique=False)
    op.create_table('premium_subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_plan_id', sa.Uuid(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='subscription_status'), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_plan_id'], ['premium_plans.id'], name=op.f('fk_premium_subscriptions_current_plan_id_premium_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_premium_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_premium_subscriptions')),
    sa.UniqueConstraint('user_id', name='uq_premium_subscriptions_user_id')
    )
    op.create_index(op.f('ix_premium_subscriptions_user_id'), 'premium_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_premium_subscriptions_user_id'), table_name='premium_subscriptions')
    op.drop_table('premium_subscriptions')
    op.drop_index(op.f('ix_premium_payment_orders_user_id'), table_name='premium_payment_orders')
    op.drop_index(op.f('ix_premium_payment_orders_invoice_number'), table_name='premium_payment_orders')
    op.drop_table('premium_payment_orders')
    op.drop_table('premium_plans')
    # ### end Alembic commands ###
