<script setup lang="ts">
import { h, onMounted, ref } from "vue"
import { useRoute, useRouter, RouterLink } from "vue-router"
import { ArrowLeft } from "lucide-vue-next"
import { NButton, NCard, NDescriptions, NDescriptionsItem, NInput, NSpace } from "naive-ui"
import JsonViewer from "@/components/common/JsonViewer.vue"
import StatusTag from "@/components/common/StatusTag.vue"
import ErrorState from "@/components/common/ErrorState.vue"
import { feedback } from "@/lib/feedback"
import { fmtDateTime, fmtVnd } from "@/lib/format"
import { paymentsApi, type PaymentDetail } from "@/lib/api/payments"

const route = useRoute(); const router = useRouter(); const payment = ref<PaymentDetail | null>(null); const loading = ref(true); const error = ref<string | null>(null)
async function load() { loading.value = true; error.value = null; try { payment.value = await paymentsApi.get(String(route.params.paymentId)) } catch (err) { error.value = err instanceof Error ? err.message : "Không thể tải đơn hàng" } finally { loading.value = false } }
function refund() { if (!payment.value) return; const reason = ref(""); feedback.dialog?.warning({ title: "Hoàn tiền đơn hàng?", content: () => h(NInput, { value: reason.value, type: "textarea", placeholder: "Lý do hoàn tiền", onUpdateValue: (v: string) => { reason.value = v } }), positiveText: "Hoàn tiền", negativeText: "Hủy", onPositiveClick: async () => { if (!reason.value.trim()) { feedback.message?.error("Lý do bắt buộc"); return false } payment.value = await paymentsApi.refund(payment.value!.id, reason.value); feedback.message?.success("Đã hoàn tiền") } }) }
function reconcile() { if (!payment.value) return; feedback.dialog?.warning({ title: "Đối soát thủ công?", content: payment.value.invoiceNumber, positiveText: "Reconcile", negativeText: "Hủy", onPositiveClick: async () => { const res = await paymentsApi.reconcile(payment.value!.id); feedback.message?.success(res.status === "reconciled" ? "Reconcile thành công" : "Không tìm thấy IPN khớp"); await load() } }) }
onMounted(() => void load())
</script>
<template><div class="page-stack"><div class="page-header"><div><n-button quaternary size="small" @click="router.back()"><template #icon><ArrowLeft :size="16" /></template>Quay lại</n-button><h1 class="page-title">{{ payment?.invoiceNumber ?? 'Chi tiết thanh toán' }}</h1><p class="page-subtitle mono">{{ route.params.paymentId }}</p></div><n-space v-if="payment"><n-button v-if="payment.status === 'paid'" type="error" @click="refund">Hoàn tiền</n-button><n-button v-if="payment.status === 'pending'" secondary @click="reconcile">Reconcile</n-button></n-space></div><ErrorState v-if="error" :message="error" @retry="load" /><n-card v-if="payment" :loading="loading"><n-descriptions bordered :column="2"><n-descriptions-item label="Số tiền">{{ fmtVnd(payment.amountVnd) }}</n-descriptions-item><n-descriptions-item label="Trạng thái"><StatusTag :status="payment.status" /></n-descriptions-item><n-descriptions-item label="User"><RouterLink :to="`/users/${payment.userId}`">{{ payment.userEmail ?? payment.userId }}</RouterLink></n-descriptions-item><n-descriptions-item label="Gói">{{ payment.planName ?? payment.planCode ?? '-' }}</n-descriptions-item><n-descriptions-item label="Tạo lúc">{{ fmtDateTime(payment.createdAt) }}</n-descriptions-item><n-descriptions-item label="Thanh toán lúc">{{ payment.paidAt ? fmtDateTime(payment.paidAt) : '-' }}</n-descriptions-item><n-descriptions-item v-if="payment.subscriptionId" label="Thuê bao"><RouterLink :to="`/subscriptions/${payment.subscriptionId}`">{{ payment.subscriptionId }}</RouterLink></n-descriptions-item><n-descriptions-item v-if="payment.grantNote" label="Ghi chú">{{ payment.grantNote }}</n-descriptions-item></n-descriptions></n-card><n-card v-if="payment?.rawIpn" title="Raw IPN"><JsonViewer :data="payment.rawIpn" /></n-card><n-card v-if="payment?.ipnLogs.length" title="IPN Logs"><JsonViewer :data="payment.ipnLogs" /></n-card></div></template>
